/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import { AchInstrument, achInstrumentSchema } from '../achInstrument.js';
import { PassToken, passTokenSchema } from '../passToken.js';

/** This is a container type for one-of types. */
export type AchInstruments = AchInstrument | PassToken;

const discriminatorMap = {
  'ach': achInstrumentSchema,
  'token/pass': passTokenSchema,
};

export const achInstrumentsSchema: Schema<AchInstruments> = oneOf(
  [achInstrumentSchema, passTokenSchema],
  discriminatorMap,
  'type'
);

export namespace AchInstruments {
  /**
   * Validation method to narrow down union type to AchInstrument type case.
   *
   * This is ACH instrument case.
   */
  export function isAchInstrument(value: unknown): value is AchInstrument {
    return isMappedValueValidForSchema(value, achInstrumentSchema);
  }

  /**
   * Validation method to narrow down union type to PassToken type case.
   *
   * This is PASS Token case.
   */
  export function isPassToken(value: unknown): value is PassToken {
    return isMappedValueValidForSchema(value, passTokenSchema);
  }
}
