/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import { AccessToken, accessTokenSchema } from '../accessToken.js';
import { CardCheckout, cardCheckoutSchema } from '../cardCheckout.js';
import {
  KeyedClearInstrument,
  keyedClearInstrumentSchema,
} from '../keyedClearInstrument.js';
import { PassToken, passTokenSchema } from '../passToken.js';
import {
  WorldpayOmniToken,
  worldpayOmniTokenSchema,
} from '../worldpayOmniToken.js';

/** This is a container type for one-of types. */
export type EcomCardInstruments =
  | KeyedClearInstrument
  | WorldpayOmniToken
  | PassToken
  | AccessToken
  | CardCheckout;

const discriminatorMap = {
  'keyed/clear': keyedClearInstrumentSchema,
  'token/omni': worldpayOmniTokenSchema,
  'token/pass': passTokenSchema,
  'token/access': accessTokenSchema,
  'checkout': cardCheckoutSchema,
};

export const ecomCardInstrumentsSchema: Schema<EcomCardInstruments> = oneOf(
  [
    keyedClearInstrumentSchema,
    worldpayOmniTokenSchema,
    passTokenSchema,
    accessTokenSchema,
    cardCheckoutSchema,
  ],
  discriminatorMap,
  'type'
);

export namespace EcomCardInstruments {
  /**
   * Validation method to narrow down union type to KeyedClearInstrument type case.
   *
   * This is Keyed Clear Instrument case.
   */
  export function isKeyedClearInstrument(
    value: unknown
  ): value is KeyedClearInstrument {
    return isMappedValueValidForSchema(value, keyedClearInstrumentSchema);
  }

  /**
   * Validation method to narrow down union type to WorldpayOmniToken type case.
   *
   * This is Worldpay OmniToken case.
   */
  export function isWorldpayOmniToken(
    value: unknown
  ): value is WorldpayOmniToken {
    return isMappedValueValidForSchema(value, worldpayOmniTokenSchema);
  }

  /**
   * Validation method to narrow down union type to PassToken type case.
   *
   * This is PASS Token case.
   */
  export function isPassToken(value: unknown): value is PassToken {
    return isMappedValueValidForSchema(value, passTokenSchema);
  }

  /**
   * Validation method to narrow down union type to AccessToken type case.
   *
   * This is Access Token case.
   */
  export function isAccessToken(value: unknown): value is AccessToken {
    return isMappedValueValidForSchema(value, accessTokenSchema);
  }

  /**
   * Validation method to narrow down union type to CardCheckout type case.
   *
   * This is card checkout case.
   */
  export function isCardCheckout(value: unknown): value is CardCheckout {
    return isMappedValueValidForSchema(value, cardCheckoutSchema);
  }
}
