/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import { AchResponseData, achResponseDataSchema } from '../achResponseData.js';
import {
  CardResponseAuth,
  cardResponseAuthSchema,
} from '../cardResponseAuth.js';

/** This is a container type for one-of types. */
export type PaymentMethodResponseAuth = CardResponseAuth | AchResponseData;

const discriminatorMap = {
  'card': cardResponseAuthSchema,
  'ach': achResponseDataSchema,
};

export const paymentMethodResponseAuthSchema: Schema<PaymentMethodResponseAuth> = oneOf(
  [cardResponseAuthSchema, achResponseDataSchema],
  discriminatorMap,
  'type'
);

export namespace PaymentMethodResponseAuth {
  /**
   * Validation method to narrow down union type to CardResponseAuth type case.
   *
   * This is cardResponseAuth case.
   */
  export function isCardResponseAuth(
    value: unknown
  ): value is CardResponseAuth {
    return isMappedValueValidForSchema(value, cardResponseAuthSchema);
  }

  /**
   * Validation method to narrow down union type to AchResponseData type case.
   *
   * This is ACH Response Data case.
   */
  export function isAchResponseData(value: unknown): value is AchResponseData {
    return isMappedValueValidForSchema(value, achResponseDataSchema);
  }
}
