/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  CardResponseRetrieval,
  cardResponseRetrievalSchema,
} from '../cardResponseRetrieval.js';
import {
  RetrievalAchData,
  retrievalAchDataSchema,
} from '../retrievalAchData.js';

/** This is a container type for one-of types. */
export type PaymentMethodResponseRetrieval =
  | CardResponseRetrieval
  | RetrievalAchData;

const discriminatorMap = {
  'card': cardResponseRetrievalSchema,
  'ach': retrievalAchDataSchema,
};

export const paymentMethodResponseRetrievalSchema: Schema<PaymentMethodResponseRetrieval> = oneOf(
  [cardResponseRetrievalSchema, retrievalAchDataSchema],
  discriminatorMap,
  'type'
);

export namespace PaymentMethodResponseRetrieval {
  /**
   * Validation method to narrow down union type to CardResponseRetrieval type case.
   *
   * This is cardResponseRetrieval case.
   */
  export function isCardResponseRetrieval(
    value: unknown
  ): value is CardResponseRetrieval {
    return isMappedValueValidForSchema(value, cardResponseRetrievalSchema);
  }

  /**
   * Validation method to narrow down union type to RetrievalAchData type case.
   *
   * This is Retrieval ACH data case.
   */
  export function isRetrievalAchData(
    value: unknown
  ): value is RetrievalAchData {
    return isMappedValueValidForSchema(value, retrievalAchDataSchema);
  }
}
