/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  AchPaymentMethod,
  achPaymentMethodSchema,
} from '../achPaymentMethod.js';
import {
  PosCardPaymentMethodRefund,
  posCardPaymentMethodRefundSchema,
} from '../posCardPaymentMethodRefund.js';
import {
  PosEbtPaymentMethod,
  posEbtPaymentMethodSchema,
} from '../posEbtPaymentMethod.js';
import {
  PosMerchantClosedLoopGiftCardPaymentMethodRefund,
  posMerchantClosedLoopGiftCardPaymentMethodRefundSchema,
} from '../posMerchantClosedLoopGiftCardPaymentMethodRefund.js';

/** This is a container type for one-of types. */
export type PosPaymentMethodsRefund =
  | PosCardPaymentMethodRefund
  | PosMerchantClosedLoopGiftCardPaymentMethodRefund
  | PosEbtPaymentMethod
  | AchPaymentMethod;

const discriminatorMap = {
  'card': posCardPaymentMethodRefundSchema,
  'gift': posMerchantClosedLoopGiftCardPaymentMethodRefundSchema,
  'ebt': posEbtPaymentMethodSchema,
  'ach': achPaymentMethodSchema,
};

export const posPaymentMethodsRefundSchema: Schema<PosPaymentMethodsRefund> = oneOf(
  [
    posCardPaymentMethodRefundSchema,
    posMerchantClosedLoopGiftCardPaymentMethodRefundSchema,
    posEbtPaymentMethodSchema,
    achPaymentMethodSchema,
  ],
  discriminatorMap,
  'type'
);

export namespace PosPaymentMethodsRefund {
  /**
   * Validation method to narrow down union type to PosCardPaymentMethodRefund type case.
   *
   * This is POS Card Payment Method (Refund) case.
   */
  export function isPosCardPaymentMethodRefund(
    value: unknown
  ): value is PosCardPaymentMethodRefund {
    return isMappedValueValidForSchema(value, posCardPaymentMethodRefundSchema);
  }

  /**
   * Validation method to narrow down union type to PosMerchantClosedLoopGiftCardPaymentMethodRefund type case.
   *
   * This is POS Merchant (Closed Loop) Gift Card Payment Method (Refund) case.
   */
  export function isPosMerchantClosedLoopGiftCardPaymentMethodRefund(
    value: unknown
  ): value is PosMerchantClosedLoopGiftCardPaymentMethodRefund {
    return isMappedValueValidForSchema(
      value,
      posMerchantClosedLoopGiftCardPaymentMethodRefundSchema
    );
  }

  /**
   * Validation method to narrow down union type to PosEbtPaymentMethod type case.
   *
   * This is POS EBT Payment Method case.
   */
  export function isPosEbtPaymentMethod(
    value: unknown
  ): value is PosEbtPaymentMethod {
    return isMappedValueValidForSchema(value, posEbtPaymentMethodSchema);
  }

  /**
   * Validation method to narrow down union type to AchPaymentMethod type case.
   *
   * This is ACH payment method case.
   */
  export function isAchPaymentMethod(
    value: unknown
  ): value is AchPaymentMethod {
    return isMappedValueValidForSchema(value, achPaymentMethodSchema);
  }
}
