/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  AchPaymentMethod,
  achPaymentMethodSchema,
} from '../achPaymentMethod.js';
import {
  PosCardPaymentMethodCreatePayment,
  posCardPaymentMethodCreatePaymentSchema,
} from '../posCardPaymentMethodCreatePayment.js';
import {
  PosEbtPaymentMethod,
  posEbtPaymentMethodSchema,
} from '../posEbtPaymentMethod.js';
import {
  PosEwicPaymentMethod,
  posEwicPaymentMethodSchema,
} from '../posEwicPaymentMethod.js';
import {
  PosMerchantClosedLoopGiftCardPaymentMethodCreatePayment,
  posMerchantClosedLoopGiftCardPaymentMethodCreatePaymentSchema,
} from '../posMerchantClosedLoopGiftCardPaymentMethodCreatePayment.js';

/** This is a container type for one-of types. */
export type PosPaymentMethodsAuth =
  | PosCardPaymentMethodCreatePayment
  | PosMerchantClosedLoopGiftCardPaymentMethodCreatePayment
  | PosEbtPaymentMethod
  | PosEwicPaymentMethod
  | AchPaymentMethod;

const discriminatorMap = {
  'card': posCardPaymentMethodCreatePaymentSchema,
  'gift': posMerchantClosedLoopGiftCardPaymentMethodCreatePaymentSchema,
  'ebt': posEbtPaymentMethodSchema,
  'ewic': posEwicPaymentMethodSchema,
  'ach': achPaymentMethodSchema,
};

export const posPaymentMethodsAuthSchema: Schema<PosPaymentMethodsAuth> = oneOf(
  [
    posCardPaymentMethodCreatePaymentSchema,
    posMerchantClosedLoopGiftCardPaymentMethodCreatePaymentSchema,
    posEbtPaymentMethodSchema,
    posEwicPaymentMethodSchema,
    achPaymentMethodSchema,
  ],
  discriminatorMap,
  'type'
);

export namespace PosPaymentMethodsAuth {
  /**
   * Validation method to narrow down union type to PosCardPaymentMethodCreatePayment type case.
   *
   * This is POS Card Payment Method (Create Payment) case.
   */
  export function isPosCardPaymentMethodCreatePayment(
    value: unknown
  ): value is PosCardPaymentMethodCreatePayment {
    return isMappedValueValidForSchema(
      value,
      posCardPaymentMethodCreatePaymentSchema
    );
  }

  /**
   * Validation method to narrow down union type to PosMerchantClosedLoopGiftCardPaymentMethodCreatePayment type case.
   *
   * This is POS Merchant (Closed Loop) Gift Card Payment Method (Create Payment) case.
   */
  export function isPosMerchantClosedLoopGiftCardPaymentMethodCreatePayment(
    value: unknown
  ): value is PosMerchantClosedLoopGiftCardPaymentMethodCreatePayment {
    return isMappedValueValidForSchema(
      value,
      posMerchantClosedLoopGiftCardPaymentMethodCreatePaymentSchema
    );
  }

  /**
   * Validation method to narrow down union type to PosEbtPaymentMethod type case.
   *
   * This is POS EBT Payment Method case.
   */
  export function isPosEbtPaymentMethod(
    value: unknown
  ): value is PosEbtPaymentMethod {
    return isMappedValueValidForSchema(value, posEbtPaymentMethodSchema);
  }

  /**
   * Validation method to narrow down union type to PosEwicPaymentMethod type case.
   *
   * This is POS EWIC Payment Method case.
   */
  export function isPosEwicPaymentMethod(
    value: unknown
  ): value is PosEwicPaymentMethod {
    return isMappedValueValidForSchema(value, posEwicPaymentMethodSchema);
  }

  /**
   * Validation method to narrow down union type to AchPaymentMethod type case.
   *
   * This is ACH payment method case.
   */
  export function isAchPaymentMethod(
    value: unknown
  ): value is AchPaymentMethod {
    return isMappedValueValidForSchema(value, achPaymentMethodSchema);
  }
}
