/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { isMappedValueValidForSchema, oneOf, Schema } from '../../schema.js';
import {
  ExternalProvider,
  externalProviderSchema,
} from '../externalProvider.js';
import { Integrated, integratedSchema } from '../integrated.js';

/** This is a container type for one-of types. */
export type Threeds = Integrated | ExternalProvider;

const discriminatorMap = {
  'integrated': integratedSchema,
  'externalProvider': externalProviderSchema,
};

export const threedsSchema: Schema<Threeds> = oneOf(
  [integratedSchema, externalProviderSchema],
  discriminatorMap,
  'type'
);

export namespace Threeds {
  /**
   * Validation method to narrow down union type to Integrated type case.
   *
   * This is integrated case.
   */
  export function isIntegrated(value: unknown): value is Integrated {
    return isMappedValueValidForSchema(value, integratedSchema);
  }

  /**
   * Validation method to narrow down union type to ExternalProvider type case.
   *
   * This is externalProvider case.
   */
  export function isExternalProvider(
    value: unknown
  ): value is ExternalProvider {
    return isMappedValueValidForSchema(value, externalProviderSchema);
  }
}
