/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { SystemError } from '../models/systemError.js';

/**
 * Creates an instance of ProblemDetails500
 */
interface ProblemDetails500 {
  /**
   * Absolute URI that identifies the problem type.  When dereferenced,
   * it SHOULD provide human-readable documentation for the problem type
   * (e.g., using HTML).
   */
  type: string;
  /** Short, human-readable summary of the problem type; for example, Service Unavailable. */
  title: string;
  /** HTTP status code generated by the origin server for this occurrence of the problem. */
  status: number;
  /** Human-readable explanation specific to this occurrence of the problem. */
  detail: string;
  errors?: SystemError[];
  additionalProperties?: Record<string, unknown>;
}

export class ProblemDetails500Error extends ApiError<ProblemDetails500> {}
