/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiError } from '../core.js';
import { NotFoundError } from '../models/notFoundError.js';

/**
 * Creates an instance of ProblemDetails404
 */
interface ProblemDetails404 {
  /**
   * Absolute URI that identifies the problem type.  When dereferenced,
   * it SHOULD provide human-readable documentation for the problem type
   * (e.g., using HTML).
   */
  type: string;
  /**
   * Short, human-readable summary of the problem type
   * example: Resource Not Found
   */
  title: string;
  /** HTTP status code generated by the origin server for this occurrence of the problem. */
  status: number;
  /** Human-readable explanation specific to this occurrence of the problem. */
  detail: string;
  errors?: NotFoundError[];
  additionalProperties?: Record<string, unknown>;
}

export class ProblemDetails404Error extends ApiError<ProblemDetails404> {}
