/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { getClientPcrtRequestSchema } from '../../models/getClientPcrtRequest.js';
import {
  lazy,
  number,
  optional,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const getPcrtMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    body: ['body', lazy(() => getClientPcrtRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

