/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { cancelPaymentRequestSchema } from '../../models/cancelPaymentRequest.js';
import { capturePaymentRequestSchema } from '../../models/capturePaymentRequest.js';
import { createPaymentRequestSchema } from '../../models/createPaymentRequest.js';
import { incrementalAuthorizationRequestSchema } from '../../models/incrementalAuthorizationRequest.js';
import { refundRequestReferencedSchema } from '../../models/refundRequestReferenced.js';
import { refundRequestUnreferencedSchema } from '../../models/refundRequestUnreferenced.js';
import { voidRequestSchema } from '../../models/voidRequest.js';
import {
  lazy,
  number,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const createPaymentMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    body: ['body', lazy(() => createPaymentRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const retrievePaymentMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    merchantId: ['merchantId', string()],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const incrementalAuthMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    body: ['body', lazy(() => incrementalAuthorizationRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const cancelPaymentMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    body: ['body', lazy(() => cancelPaymentRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const capturePaymentMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    body: ['body', lazy(() => capturePaymentRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const retrieveCaptureMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    captureId: ['captureId', string()],
    merchantId: ['merchantId', string()],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const voidCaptureMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    captureId: ['captureId', string()],
    body: ['body', lazy(() => voidRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const referencedRefundMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    body: ['body', lazy(() => refundRequestReferencedSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const retrieveReferencedRefundMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    refundId: ['refundId', string()],
    merchantId: ['merchantId', string()],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const voidReferencedRefundMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    id: ['id', string()],
    refundId: ['refundId', string()],
    body: ['body', lazy(() => voidRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const unreferencedRefundMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    body: ['body', lazy(() => refundRequestUnreferencedSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const voidUnreferencedRefundMetadataRequestSchema = typedExpandoObject(
  {
    wpIdempotencyKey: ['WP-Idempotency-Key', string()],
    wpApiVersion: ['WP-Api-Version', number()],
    refundId: ['refundId', string()],
    body: ['body', lazy(() => voidRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

