/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { updatePaymentScheduleRequestSchema } from '../../models/updatePaymentScheduleRequest.js';
import {
  lazy,
  number,
  optional,
  string,
  typedExpandoObject,
  unknown,
} from '../../schema.js';

export const queryScheduleMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    scheduleId: ['scheduleId', string()],
    merchantId: ['merchantId', string()],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const updateScheduleMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    scheduleId: ['scheduleId', string()],
    body: ['body', lazy(() => updatePaymentScheduleRequestSchema)],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

export const deleteScheduleMetadataRequestSchema = typedExpandoObject(
  {
    wpApiVersion: ['WP-Api-Version', number()],
    scheduleId: ['scheduleId', string()],
    merchantId: ['merchantId', string()],
    wpAccountId: ['WP-AccountId', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);

