/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HttpClientOptions } from './clientAdapter.js';
import { PartialLoggingOptions } from './core.js';

/** An interface for all configuration parameters required by the SDK. */
export interface Configuration {
  timeout: number;
  environment: Environment;
  customHeaderAuthenticationCredentials?: {
    'Authorization': string;
  };
  httpClientOptions?: Partial<HttpClientOptions>;
  unstable_httpClientOptions?: any;
  logging?: PartialLoggingOptions;
}

/** Environments available for API */
export enum Environment {
  Production = 'production',
  Certification = 'certification',
}

export function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.EXPRESS_PAYMENTS_API_LIB_ENVIRONMENT;
  const timeout = process.env.EXPRESS_PAYMENTS_API_LIB_TIMEOUT;
  const authorization = process.env.EXPRESS_PAYMENTS_API_LIB_AUTHORIZATION;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (authorization !== undefined) {
    config.customHeaderAuthenticationCredentials = {
      Authorization: authorization,
    };
  }

  return config;
}
