/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Access token instrument */
export interface AccessToken {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** href to the token resource */
  href: string;
  /** Card verification code (CVC). Also known as Card Verification Value (CVV) */
  cvc?: string;
  /**
   * Href to the Checkout session providing the Card Verification Code (CVC)
   * __Note:__ Provide a value in `cvcSessionHref` or `cvc`, never both
   */
  cvcSessionHref?: string;
  additionalProperties?: Record<string, unknown>;
}

export const accessTokenSchema: Schema<AccessToken> = typedExpandoObject(
  {
    type: ['type', string()],
    href: ['href', string()],
    cvc: ['cvc', optional(string())],
    cvcSessionHref: ['cvcSessionHref', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
