/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for AchAccountType
 */
export enum AchAccountType {
  Checking = 'checking',
  Savings = 'savings',
}

/**
 * Schema for AchAccountType
 */
export const achAccountTypeSchema: Schema<AchAccountType> = stringEnum(
  AchAccountType
);
