/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AchAccountType, achAccountTypeSchema } from './achAccountType.js';
import { SecCode, secCodeSchema } from './secCode.js';

/** Instrument for ACH */
export interface AchInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** ACH/bank account number. */
  account: string;
  /** Routing number of the banking institution. */
  routing: string;
  /** Type of ACH account. */
  accountType?: AchAccountType;
  /** SEC codes for ACH processing */
  secCode?: SecCode;
  /** Optional check number. */
  checkNumber?: string;
  additionalProperties?: Record<string, unknown>;
}

export const achInstrumentSchema: Schema<AchInstrument> = typedExpandoObject(
  {
    type: ['type', string()],
    account: ['account', string()],
    routing: ['routing', string()],
    accountType: ['accountType', optional(achAccountTypeSchema)],
    secCode: ['secCode', optional(secCodeSchema)],
    checkNumber: ['checkNumber', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
