/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AchInstruments,
  achInstrumentsSchema,
} from './containers/achInstruments.js';
import { TokenCreate, tokenCreateSchema } from './containers/tokenCreate.js';
import { Scheduled, scheduledSchema } from './scheduled.js';

/** Payment Method for ACH */
export interface AchPaymentMethod {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Instruments for ACH processing */
  instrument: AchInstruments;
  /** Create a token for use in future payments */
  createToken?: TokenCreate;
  /** Customer agreement data limited to scheduled payments */
  customerAgrement?: Scheduled;
  additionalProperties?: Record<string, unknown>;
}

export const achPaymentMethodSchema: Schema<AchPaymentMethod> = typedExpandoObject(
  {
    type: ['type', string()],
    instrument: ['instrument', achInstrumentsSchema],
    createToken: ['createToken', optional(tokenCreateSchema)],
    customerAgrement: [
      'customerAgrement',
      optional(lazy(() => scheduledSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
