/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  TokenResponse,
  tokenResponseSchema,
} from './containers/tokenResponse.js';

/** Response data specific to ACH payment method. */
export interface AchResponseData {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Token response. */
  token?: TokenResponse;
}

export const achResponseDataSchema: Schema<AchResponseData> = object({
  type: ['type', string()],
  token: ['token', optional(tokenResponseSchema)],
});
