/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** HATEOAS links for response payloads. */
export interface Actions {
  /** URI to act on this Payment resource; this could be a capture, reversal, refund, or void, depending upon payment state. */
  href?: string;
  method?: string;
  additionalProperties?: Record<string, unknown>;
}

export const actionsSchema: Schema<Actions> = typedExpandoObject(
  {
    href: ['href', optional(string())],
    method: ['method', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
