/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema } from '../schema.js';

/** Other (optional) amounts that are included in the Total Authorization Amount, for EBT and eWIC transactions */
export interface AdditionalAmountsEbtEwic {
  /** Contains the convenience fee associated with a transaction. This value is for reporting purposes only, as the Transaction Amount field should included this amount in the total. */
  convenienceFee?: bigint;
  /** Sales tax amount. */
  salesTax?: bigint;
}

export const additionalAmountsEbtEwicSchema: Schema<AdditionalAmountsEbtEwic> = object(
  {
    convenienceFee: ['convenienceFee', optional(bigint())],
    salesTax: ['salesTax', optional(bigint())],
  }
);
