/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema } from '../schema.js';

/** Other (optional) amounts that are included in the Total Authorization Amount, for credit card present */
export interface AdditionalAmountsCreditCardPresent {
  /** On requests, this value represents the amount of cash back requested by the cardholder.  On replies, this value may be provided to represent the amount of cash back authorized by the issuer. */
  cashBack?: bigint;
  /** Indicates that the consumer is charged a transaction fee for enacting the transaction by the terminal owner. For non-POS credit card transactions, this fee is not included in the Transaction Amount field. The consumer performing the transaction is charged for the Transaction Amount plus Surcharge Fee Amount. For POS credit card transactions, include this fee in the Transaction Amount field. The consumer performing the transaction is charged only for the value in the Transaction Amount field. */
  surcharge?: bigint;
  /** Contains the convenience fee associated with a transaction. This value is for reporting purposes only, as the Transaction Amount field should included this amount in the total. */
  convenienceFee?: bigint;
  /** Contains the tip amount associated with a transaction. This value is for reporting purposes only, as the Transaction Amount field should include this amount in the total. */
  tip?: bigint;
  /** Sales tax amount. */
  salesTax?: bigint;
}

export const additionalAmountsCreditCardPresentSchema: Schema<AdditionalAmountsCreditCardPresent> = object(
  {
    cashBack: ['cashBack', optional(bigint())],
    surcharge: ['surcharge', optional(bigint())],
    convenienceFee: ['convenienceFee', optional(bigint())],
    tip: ['tip', optional(bigint())],
    salesTax: ['salesTax', optional(bigint())],
  }
);
