/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CountryCode, countryCodeSchema } from './countryCode.js';

/** Address data */
export interface Address {
  address1: string;
  address2?: string;
  address3?: string;
  /** Only optional for country code SG (Singapore) */
  city?: string;
  /** Supported ISO 3166-1 alpha-2 country code. */
  countryCode: CountryCode;
  /** Only optional for country code IE (Ireland) */
  postalCode?: string;
  state?: string;
  additionalProperties?: Record<string, unknown>;
}

export const addressSchema: Schema<Address> = typedExpandoObject(
  {
    address1: ['address1', string()],
    address2: ['address2', optional(string())],
    address3: ['address3', optional(string())],
    city: ['city', optional(string())],
    countryCode: ['countryCode', countryCodeSchema],
    postalCode: ['postalCode', optional(string())],
    state: ['state', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
