/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { CaptureBalances, captureBalancesSchema } from './captureBalances.js';

/** Total amounts including currency associated with this capture. */
export interface AmountsCaptureRetrieval {
  /** Balances data for response payloads specific to captures; note that these balance values only reflect the specific capture and void capture operations - they will not be decremented by operations such as cancellations. For a complete picture of the payment lifecycle, perform a retrieval on the payment resource itself. */
  balances: CaptureBalances;
  /** Three-digit currency code. See list of supported currencies. */
  currency: string;
}

export const amountsCaptureRetrievalSchema: Schema<AmountsCaptureRetrieval> = object(
  {
    balances: ['balances', lazy(() => captureBalancesSchema)],
    currency: ['currency', string()],
  }
);
