/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** the value and currency */
export interface AmountWithCurrency1 {
  /** Three-digit currency code. See list of supported currencies. */
  currency: string;
  /** Net total of the payment resource at the time of retrieval, given all operations (credits/debits); this is the *effective balance*. */
  value: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const amountWithCurrency1Schema: Schema<AmountWithCurrency1> = typedExpandoObject(
  { currency: ['currency', string()], value: ['value', bigint()] },
  'additionalProperties',
  optional(unknown())
);
