/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  ReferencedRefundBalances,
  referencedRefundBalancesSchema,
} from './referencedRefundBalances.js';

/** Total amounts including currency associated with this refund. */
export interface AmountsRefundRetrieval {
  /** Balances data for response payloads specific to referenced refunds; note that these balance values only reflect the specific refund and void refund operations - they will not be decremented by operations such as cancellations. For a complete picture of the payment lifecycle, perform a retrieval on the payment resource itself. */
  balances: ReferencedRefundBalances;
  /** Three-digit currency code. See list of supported currencies. */
  currency: string;
}

export const amountsRefundRetrievalSchema: Schema<AmountsRefundRetrieval> = object(
  {
    balances: ['balances', lazy(() => referencedRefundBalancesSchema)],
    currency: ['currency', string()],
  }
);
