/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, lazy, object, optional, Schema } from '../schema.js';
import {
  AdditionalAmountsCreditCardPresent,
  additionalAmountsCreditCardPresentSchema,
} from './additionalAmountsCreditCardPresent.js';

/** Total Amount (and optionally a breakdown) to capture for this transaction. */
export interface AmountsCapture {
  /** Total Amount for this transaction in minor currency units **with no decimal point**. For example, $1.00 USD would be written as 100. For card verification requests, set amount to 0 (zero). */
  totalAmount: bigint;
  /** Other (optional) amounts that are included in the Total Authorization Amount, for credit card present */
  otherAmounts?: AdditionalAmountsCreditCardPresent;
}

export const amountsCaptureSchema: Schema<AmountsCapture> = object({
  totalAmount: ['totalAmount', bigint()],
  otherAmounts: [
    'otherAmounts',
    optional(lazy(() => additionalAmountsCreditCardPresentSchema)),
  ],
});
