/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, Schema } from '../schema.js';
import { Currency, currencySchema } from './currency.js';

/** The Total Amount including currency (and optionally a breakdown) associated with this payment or follow-on request */
export interface AmountWithCurrency {
  /** "The three (3) character [ISO-4217 currency code](page:reference/iso-currency-codes) for the amount." */
  currency: Currency;
  /** Net total of the payment resource at the time of retrieval, given all operations (credits/debits); this is the *effective balance* */
  value: bigint;
}

export const amountWithCurrencySchema: Schema<AmountWithCurrency> = object({
  currency: ['currency', currencySchema],
  value: ['value', bigint()],
});
