/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Authorization error */
export interface AuthorizationError {
  /** High-level, human-readable classification of the error. */
  title?: string;
  /** Human-readable description of the authentication or authorization error. */
  message?: string;
}

export const authorizationErrorSchema: Schema<AuthorizationError> = object({
  title: ['title', optional(string())],
  message: ['message', optional(string())],
});
