/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import {
  BalancesCurrentApprovedTotal,
  balancesCurrentApprovedTotalSchema,
} from './balancesCurrentApprovedTotal.js';
import {
  BalancesRequestedApprovedTotal,
  balancesRequestedApprovedTotalSchema,
} from './balancesRequestedApprovedTotal.js';

/** Balances data for response payloads; except where noted, balance amounts (example: _authorizations.approved_) will reflect the original operation performed  and will not be incremented or decremented based on other operations (example: partial cancellation). Interrogate the "total" field to obtain a net balance amount of the payment. */
export interface Balances {
  /** Returns generalized balance data for requested, approved, and total requests. */
  authorizations: BalancesRequestedApprovedTotal;
  /** Returns generalized balance data for current, available, and total requests. */
  captures: BalancesCurrentApprovedTotal;
  /** Returns generalized balance data for current, available, and total requests. */
  refunds: BalancesCurrentApprovedTotal;
  /** Returns generalized balance data for current, available, and total requests. */
  cancellations: BalancesCurrentApprovedTotal;
}

export const balancesSchema: Schema<Balances> = object({
  authorizations: [
    'authorizations',
    lazy(() => balancesRequestedApprovedTotalSchema),
  ],
  captures: ['captures', lazy(() => balancesCurrentApprovedTotalSchema)],
  refunds: ['refunds', lazy(() => balancesCurrentApprovedTotalSchema)],
  cancellations: [
    'cancellations',
    lazy(() => balancesCurrentApprovedTotalSchema),
  ],
});
