/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Returns generalized balance data for current, available, and total requests. */
export interface BalancesCurrentApprovedTotal {
  /** Current balance of this operation type. */
  current?: number;
  /** Amount available (remaining) for this operation type. */
  available?: number;
  /** Total number of requests of this operation type submitted by the caller to reach the current balance. */
  totalRequests?: number;
  additionalProperties?: Record<string, unknown>;
}

export const balancesCurrentApprovedTotalSchema: Schema<BalancesCurrentApprovedTotal> = typedExpandoObject(
  {
    current: ['current', optional(number())],
    available: ['available', optional(number())],
    totalRequests: ['totalRequests', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
