/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Returns generalized balance data for requested, approved, and total requests. */
export interface BalancesRequestedApprovedTotal {
  /** Full amount requested for this particular operation type; this may not match the full approved or current amount on the payment. */
  requested?: bigint;
  /** Approved amount for this operation type. */
  approved?: bigint;
  /** Total number of requests of this operation type submitted by the caller to reach the current balance. */
  totalRequests?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const balancesRequestedApprovedTotalSchema: Schema<BalancesRequestedApprovedTotal> = typedExpandoObject(
  {
    requested: ['requested', optional(bigint())],
    approved: ['approved', optional(bigint())],
    totalRequests: ['totalRequests', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
