/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Value, valueSchema } from './value.js';

/** Summary of the open batch, as of the completion of the current operation. */
export interface BatchResponse {
  /** the value and currency */
  amount?: Value;
  /** Four-digit identifier of the current batch. */
  id?: number;
  additionalProperties?: Record<string, unknown>;
}

export const batchResponseSchema: Schema<BatchResponse> = typedExpandoObject(
  {
    amount: ['amount', optional(lazy(() => valueSchema))],
    id: ['id', optional(number())],
  },
  'additionalProperties',
  optional(unknown())
);
