/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';

/** Billing information. */
export interface Billing {
  /** Customers first name */
  firstName?: string;
  /** Customers last name */
  lastName?: string;
  /** Address data */
  address?: Address;
  additionalProperties?: Record<string, unknown>;
}

export const billingSchema: Schema<Billing> = typedExpandoObject(
  {
    firstName: ['firstName', optional(string())],
    lastName: ['lastName', optional(string())],
    address: ['address', optional(lazy(() => addressSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
