/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AmountsCapture, amountsCaptureSchema } from './amountsCapture.js';
import { EnhancedData, enhancedDataSchema } from './containers/enhancedData.js';
import {
  MerchantSubsequentRequest,
  merchantSubsequentRequestSchema,
} from './merchantSubsequentRequest.js';

/** Capture this Payment */
export interface CapturePaymentRequest {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Subsequent request merchant object. */
  merchant?: MerchantSubsequentRequest;
  /** Total Amount (and optionally a breakdown) to capture for this transaction. */
  amounts?: AmountsCapture;
  /** Additional information about the transaction that for certain types of requests can reduce your interchange cost. */
  enhancedData?: EnhancedData;
  additionalProperties?: Record<string, unknown>;
}

export const capturePaymentRequestSchema: Schema<CapturePaymentRequest> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    merchant: [
      'merchant',
      optional(lazy(() => merchantSubsequentRequestSchema)),
    ],
    amounts: ['amounts', optional(lazy(() => amountsCaptureSchema))],
    enhancedData: ['enhancedData', optional(enhancedDataSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
