/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, boolean, object, optional, Schema } from '../schema.js';

/** Balances data for response payloads specific to captures; note that these balance values only reflect the specific capture and void capture operations - they will not be decremented by operations such as cancellations. For a complete picture of the payment lifecycle, perform a retrieval on the payment resource itself. */
export interface CaptureBalances {
  /** Total amount requested to be captured on this payment in minor currency units with no decimal point. For example, $1.00 USD would be written as 100. */
  current: bigint;
  /** Total amount currently available for capture on this payment. For example, $1.00 USD would be written as 100. */
  available: bigint;
  /** Flag that indicates whether this capture sub-resource has been voided. */
  voided?: boolean;
}

export const captureBalancesSchema: Schema<CaptureBalances> = object({
  current: ['current', bigint()],
  available: ['available', bigint()],
  voided: ['voided', optional(boolean())],
});
