/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AmountWithCurrency1,
  amountWithCurrency1Schema,
} from './amountWithCurrency1.js';
import {
  CapturePaymentResponseActions,
  capturePaymentResponseActionsSchema,
} from './capturePaymentResponseActions.js';
import { Links, linksSchema } from './links.js';
import {
  PaymentMethodResponseSubsequentOffline,
  paymentMethodResponseSubsequentOfflineSchema,
} from './paymentMethodResponseSubsequentOffline.js';

/** Response payload for payment capture requests */
export interface CapturePaymentResponse {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Globally unique identifer defined by Worldpay. */
  commandId?: string;
  /** Globally unique identifer defined by Worldpay. */
  captureId?: string;
  /** Outcome of the request; one of the following: captured | partially captured */
  outcome: string;
  /** Date and time, conforming to the ISO-8601 specification, that the transaction was received and processed. */
  dateTime: string;
  /** the value and currency */
  amount?: AmountWithCurrency1;
  /** Response data specific to the payment method. */
  paymentMethod?: PaymentMethodResponseSubsequentOffline;
  /** HATEOAS links for response payloads. */
  links?: Links;
  actions?: CapturePaymentResponseActions;
  additionalProperties?: Record<string, unknown>;
}

export const capturePaymentResponseSchema: Schema<CapturePaymentResponse> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    commandId: ['commandId', optional(string())],
    captureId: ['captureId', optional(string())],
    outcome: ['outcome', string()],
    dateTime: ['dateTime', string()],
    amount: ['amount', optional(lazy(() => amountWithCurrency1Schema))],
    paymentMethod: [
      'paymentMethod',
      optional(lazy(() => paymentMethodResponseSubsequentOfflineSchema)),
    ],
    links: ['_links', optional(lazy(() => linksSchema))],
    actions: [
      '_actions',
      optional(lazy(() => capturePaymentResponseActionsSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
