/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { BatchResponse, batchResponseSchema } from './batchResponse.js';
import {
  TokenResponse,
  tokenResponseSchema,
} from './containers/tokenResponse.js';
import { EmvResponse, emvResponseSchema } from './emvResponse.js';
import { Expiration, expirationSchema } from './expiration.js';
import { FraudResult, fraudResultSchema } from './fraudResult.js';
import {
  NetworkResponseAuthorizationRequest,
  networkResponseAuthorizationRequestSchema,
} from './networkResponseAuthorizationRequest.js';

/**
 * Summary of card-level information that was used in the transaction, whether submitted explicitly or
 * represented by a wallet, token, or encrypted payload.
 */
export interface CardResponseAuth {
  /** Type of payment method. */
  type: string;
  /** BIN (Bank Identification Number) for the card. */
  bin?: string;
  /** Last four digits of the card. */
  lastFour?: string;
  /** Card logo/brand of the card. */
  brand?: string;
  /** Issuer/bank of the card (if known). */
  issuer?: string;
  /** Issuer payment acccount reference. */
  paymentAccountReference?: string;
  /** Information about the expiration date. */
  expiration?: Expiration;
  /** Issuer specific data returned for an EMV transaction. */
  emvResponse?: EmvResponse;
  /** Unaltered response data from the downstream acquirer or issuer. */
  networkResponse?: NetworkResponseAuthorizationRequest;
  /** Results of an optional Fraud Check. */
  fraudResult?: FraudResult;
  /** Summary of the open batch, as of the completion of the current operation. */
  batch?: BatchResponse;
  /** Token response. */
  token?: TokenResponse;
  additionalProperties?: Record<string, unknown>;
}

export const cardResponseAuthSchema: Schema<CardResponseAuth> = typedExpandoObject(
  {
    type: ['type', string()],
    bin: ['bin', optional(string())],
    lastFour: ['lastFour', optional(string())],
    brand: ['brand', optional(string())],
    issuer: ['issuer', optional(string())],
    paymentAccountReference: ['paymentAccountReference', optional(string())],
    expiration: ['expiration', optional(lazy(() => expirationSchema))],
    emvResponse: ['emvResponse', optional(lazy(() => emvResponseSchema))],
    networkResponse: [
      'networkResponse',
      optional(lazy(() => networkResponseAuthorizationRequestSchema)),
    ],
    fraudResult: ['fraudResult', optional(lazy(() => fraudResultSchema))],
    batch: ['batch', optional(lazy(() => batchResponseSchema))],
    token: ['token', optional(tokenResponseSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
