/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema } from '../schema.js';
import { ProcessAsEnum, processAsEnumSchema } from './processAsEnum.js';

/** Options for handling the authorization request. */
export interface CardPaymentMethodOptionsRefund {
  /** Optionally specify exactly how the card should be processed. Worldpay will assume "creditOrSignatureDebit" if not specified. */
  processAs?: ProcessAsEnum;
}

export const cardPaymentMethodOptionsRefundSchema: Schema<CardPaymentMethodOptionsRefund> = object(
  { processAs: ['processAs', optional(processAsEnumSchema)] }
);
