/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for CardBrand
 */
export enum CardBrand {
  Airplus = 'airplus',
  Allstar = 'allstar',
  Amex = 'amex',
  Argencard = 'argencard',
  Aurore = 'aurore',
  Bc = 'bc',
  Cabal = 'cabal',
  Carnet = 'carnet',
  CarteBlanche = 'carteBlanche',
  CartesBancaires = 'cartesBancaires',
  Cencosud = 'cencosud',
  Coopeplus = 'coopeplus',
  Credimas = 'credimas',
  Dankort = 'dankort',
  DinersClub = 'dinersClub',
  Discover = 'discover',
  EftposAu = 'eftposAU',
  Elo = 'elo',
  Hana = 'hana',
  Hipercard = 'hipercard',
  Hyundai = 'hyundai',
  Interac = 'interac',
  Italcred = 'italcred',
  Jcb = 'jcb',
  Keyfuels = 'keyfuels',
  Kookmin = 'kookmin',
  Lotte = 'lotte',
  Maestro = 'maestro',
  Mastercard = 'mastercard',
  Naranja = 'naranja',
  Nativa = 'nativa',
  Nevada = 'nevada',
  Nexo = 'nexo',
  Nonghyup = 'nonghyup',
  Other = 'other',
  Overdrive = 'overdrive',
  Samsung = 'samsung',
  Sears = 'sears',
  Shinhan = 'shinhan',
  Sorocred = 'sorocred',
  StoredValue = 'storedValue',
  Supercharge = 'supercharge',
  Tarjeta = 'tarjeta',
  Troy = 'troy',
  Uatp = 'uatp',
  UnionPay = 'unionPay',
  Visa = 'visa',
}

/**
 * Schema for CardBrand
 */
export const cardBrandSchema: Schema<CardBrand> = stringEnum(CardBrand);
