/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Information about the expiration date for the card. */
export interface CardExpiration {
  /** Calendar month that the card expires. */
  month: number;
  /** Calendar year that the card expires. */
  year: number;
}

export const cardExpirationSchema: Schema<CardExpiration> = object({
  month: ['month', number()],
  year: ['year', number()],
});
