/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';
import { ProcessAsEnum, processAsEnumSchema } from './processAsEnum.js';

/** Options for handling the authorization request */
export interface CardPaymentMethodOptions {
  /** If true, you want to perform an address verification. */
  addressVerification?: boolean;
  /** If true, you will accept approvals for less than the total requested amount. */
  partialApproval?: boolean;
  /** Optionally specify exactly how the card should be processed. Worldpay will assume "creditOrSignatureDebit" if not specified. */
  processAs?: ProcessAsEnum;
  /** If true, you want to Authorize and Capture in a single step. */
  autoCapture?: boolean;
  /** "Pre-authorization indicates the merchant is submitting an authorization request with an estimated amount. Payment Option - autoCapture should be set to FALSE and the merchant will be submitting further incremental authorizations to increase the authorized amount. The payment will be manually captured by the merchant once the final amount is known.   Options of autoCapture and preAuthorization are mutually exclusive, will result in a error response in the event both are set to True. " */
  preAuthorization?: boolean;
}

export const cardPaymentMethodOptionsSchema: Schema<CardPaymentMethodOptions> = object(
  {
    addressVerification: ['addressVerification', optional(boolean())],
    partialApproval: ['partialApproval', optional(boolean())],
    processAs: ['processAs', optional(processAsEnumSchema)],
    autoCapture: ['autoCapture', optional(boolean())],
    preAuthorization: ['preAuthorization', optional(boolean())],
  }
);
