/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Checkout instrument */
export interface CardCheckout {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** href to the sessions resource */
  href: string;
  additionalProperties?: Record<string, unknown>;
}

export const cardCheckoutSchema: Schema<CardCheckout> = typedExpandoObject(
  { type: ['type', string()], href: ['href', string()] },
  'additionalProperties',
  optional(unknown())
);
