/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Currency
 */
export enum Currency {
  Usd = 'USD',
  Cad = 'CAD',
  Gbp = 'GBP',
}

/**
 * Schema for Currency
 */
export const currencySchema: Schema<Currency> = stringEnum(Currency);
