/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Billing, billingSchema } from './billing.js';
import { Shipping, shippingSchema } from './shipping.js';

/** Customer address data */
export interface Customer {
  /** Billing information. */
  billingAddress?: Billing;
  /** Shipping information used for fraud assessment, 3DS authentication and the payment itself. */
  shippingAddress?: Shipping;
  additionalProperties?: Record<string, unknown>;
}

export const customerSchema: Schema<Customer> = typedExpandoObject(
  {
    billingAddress: ['billingAddress', optional(lazy(() => billingSchema))],
    shippingAddress: ['shippingAddress', optional(lazy(() => shippingSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
