/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DeviceChannel
 */
export enum DeviceChannel {
  Web = 'web',
  Native = 'native',
}

/**
 * Schema for DeviceChannel
 */
export const deviceChannelSchema: Schema<DeviceChannel> = stringEnum(
  DeviceChannel
);
