/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DeviceCapabilities
 */
export enum DeviceCapabilities {
  ManualEntryOnly = 'manualEntryOnly',
  MagstripeReader = 'magstripeReader',
  ChipReader = 'chipReader',
  ContactlessChipReader = 'contactlessChipReader',
}

/**
 * Schema for DeviceCapabilities
 */
export const deviceCapabilitiesSchema: Schema<DeviceCapabilities> = stringEnum(
  DeviceCapabilities
);
