/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { DeviceChannel, deviceChannelSchema } from './deviceChannel.js';

/** An object containing device data for 3DS */
export interface DeviceData {
  /** Your customer's browser language that can be used by the issuer in risk analysis. Must conform to the language tags defined by IETF. E.g. en-GB, fr-FR */
  browserLanguage?: string;
  browserJavaEnabled?: boolean;
  browserColorDepth?: number;
  browserScreenHeight?: number;
  browserScreenWidth?: number;
  browserTz?: number;
  deviceChannel?: DeviceChannel;
  browserJavascriptEnabled?: boolean;
  /** Used by issuers as part of risk analysis and correctly displaying the challenge. Must conform to RFC 7321 */
  userAgentHeader: string;
  /** Used by the issuer to check if the customer's browser is compatible with the issuer 3DS challenge display. */
  acceptHeader: string;
  additionalProperties?: Record<string, unknown>;
}

export const deviceDataSchema: Schema<DeviceData> = typedExpandoObject(
  {
    browserLanguage: ['browserLanguage', optional(string())],
    browserJavaEnabled: ['browserJavaEnabled', optional(boolean())],
    browserColorDepth: ['browserColorDepth', optional(number())],
    browserScreenHeight: ['browserScreenHeight', optional(number())],
    browserScreenWidth: ['browserScreenWidth', optional(number())],
    browserTz: ['browserTZ', optional(number())],
    deviceChannel: ['deviceChannel', optional(deviceChannelSchema)],
    browserJavascriptEnabled: ['browserJavascriptEnabled', optional(boolean())],
    userAgentHeader: ['userAgentHeader', string()],
    acceptHeader: ['acceptHeader', string()],
  },
  'additionalProperties',
  optional(unknown())
);
