/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DeviceEnvironment
 */
export enum DeviceEnvironment {
  LocalAttended = 'localAttended',
  LocalUnattended = 'localUnattended',
  LocalSemiAttended = 'localSemiAttended',
  RemoteAttended = 'remoteAttended',
  RemoteUnattended = 'remoteUnattended',
  RemoteSemiAttended = 'remoteSemiAttended',
}

/**
 * Schema for DeviceEnvironment
 */
export const deviceEnvironmentSchema: Schema<DeviceEnvironment> = stringEnum(
  DeviceEnvironment
);
