/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EcomCardInstruments,
  ecomCardInstrumentsSchema,
} from './containers/ecomCardInstruments.js';
import { TokenCreate, tokenCreateSchema } from './containers/tokenCreate.js';

/** Ecom card payment method for refunds. */
export interface EcomCardPaymentMethodRefund {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped, Inserted or Tapped) the customer is providing the card information. */
  instrument: EcomCardInstruments;
  /** Create a token for use in future payments */
  createToken?: TokenCreate;
  additionalProperties?: Record<string, unknown>;
}

export const ecomCardPaymentMethodRefundSchema: Schema<EcomCardPaymentMethodRefund> = typedExpandoObject(
  {
    type: ['type', string()],
    instrument: ['instrument', ecomCardInstrumentsSchema],
    createToken: ['createToken', optional(tokenCreateSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
