/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EcomPaymentMethodsRefund,
  ecomPaymentMethodsRefundSchema,
} from './containers/ecomPaymentMethodsRefund.js';

/** Ecom channel for refunds. */
export interface EcomChannelRefund {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Ecom payment methods for refund. */
  paymentMethod: EcomPaymentMethodsRefund;
  additionalProperties?: Record<string, unknown>;
}

export const ecomChannelRefundSchema: Schema<EcomChannelRefund> = typedExpandoObject(
  {
    type: ['type', string()],
    paymentMethod: ['paymentMethod', ecomPaymentMethodsRefundSchema],
  },
  'additionalProperties',
  optional(unknown())
);
