/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import {
  AdditionalAmountsCardNotPresent,
  additionalAmountsCardNotPresentSchema,
} from './additionalAmountsCardNotPresent.js';
import {
  KeyedClearInstrument,
  keyedClearInstrumentSchema,
} from './keyedClearInstrument.js';
import {
  PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods,
  paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema,
} from './paymentMethodOptionsAssociatedWithNonCreditOrDebitMethods.js';

/** Information from the EBT (Electronic Funds Transfer) Card. */
export interface EComEbtPaymentMethod {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Manner in which the EBT card is presented. */
  instrument: KeyedClearInstrument;
  /** Other (optional) amounts that are included in the Total Authorization Amount, for card not present transactions */
  otherAmounts?: AdditionalAmountsCardNotPresent;
  voucher?: string;
  fnsNumber?: string;
  foodstampOnly?: boolean;
  /** Options for handling the authorization request */
  options?: PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods;
}

export const eComEbtPaymentMethodSchema: Schema<EComEbtPaymentMethod> = object({
  type: ['type', string()],
  instrument: ['instrument', lazy(() => keyedClearInstrumentSchema)],
  otherAmounts: [
    'otherAmounts',
    optional(lazy(() => additionalAmountsCardNotPresentSchema)),
  ],
  voucher: ['voucher', optional(string())],
  fnsNumber: ['fnsNumber', optional(string())],
  foodstampOnly: ['foodstampOnly', optional(boolean())],
  options: [
    'options',
    optional(
      lazy(
        () => paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema
      )
    ),
  ],
});
