/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  EcomPaymentMethodsAuth,
  ecomPaymentMethodsAuthSchema,
} from './containers/ecomPaymentMethodsAuth.js';

/** Ecom channel */
export interface EcomChannelCreatePayment {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Ecom Payment Methods */
  paymentMethod: EcomPaymentMethodsAuth;
  additionalProperties?: Record<string, unknown>;
}

export const ecomChannelCreatePaymentSchema: Schema<EcomChannelCreatePayment> = typedExpandoObject(
  {
    type: ['type', string()],
    paymentMethod: ['paymentMethod', ecomPaymentMethodsAuthSchema],
  },
  'additionalProperties',
  optional(unknown())
);
