/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EmvCardInputCode
 */
export enum EmvCardInputCode {
  ChipRead = 'chipRead',
  ContactlessChipRead = 'contactlessChipRead',
}

/**
 * Schema for EmvCardInputCode
 */
export const emvCardInputCodeSchema: Schema<EmvCardInputCode> = stringEnum(
  EmvCardInputCode
);
