/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  EmvEncryptedFormat,
  emvEncryptedFormatSchema,
} from './emvEncryptedFormat.js';

/** Objects supporting the transmission of encrypted EMV TLV tags */
export interface EmvEncryptedData {
  keySerialNumber: string;
  /** Device manufacturer and family-specific encryption format for card present transactions */
  encryptedFormat: EmvEncryptedFormat;
  encryptedEmvTlvData?: string;
}

export const emvEncryptedDataSchema: Schema<EmvEncryptedData> = object({
  keySerialNumber: ['keySerialNumber', string()],
  encryptedFormat: ['encryptedFormat', emvEncryptedFormatSchema],
  encryptedEmvTlvData: ['encryptedEmvTlvData', optional(string())],
});
