/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for EmvEncryptedFormat
 */
export enum EmvEncryptedFormat {
  Equinox = 'equinox',
  IngenicoRba = 'ingenicoRba',
  BbPosChipper = 'bbPosChipper',
  VerifoneVxLegacy = 'verifoneVxLegacy',
  VerifoneVxXpi = 'verifoneVxXpi',
  VerifoneMx = 'verifoneMx',
  IgnenicoTetraOnguardSde = 'ignenicoTetraOnguardSde',
  IngenicoTetraGeneric = 'ingenicoTetraGeneric',
  IngenicoMoby = 'ingenicoMoby',
}

/**
 * Schema for EmvEncryptedFormat
 */
export const emvEncryptedFormatSchema: Schema<EmvEncryptedFormat> = stringEnum(
  EmvEncryptedFormat
);
