/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  EmvCardInputCode,
  emvCardInputCodeSchema,
} from './emvCardInputCode.js';
import {
  EmvEncryptedData,
  emvEncryptedDataSchema,
} from './emvEncryptedData.js';
import { PinData, pinDataSchema } from './pinData.js';

/** EMV instrument for encrypted card data */
export interface EmvInstrumentEncrypted {
  /** Value indicating the specific type instance for this field. */
  type: string;
  emvTlvData: string;
  /** Objects supporting the transmission of encrypted EMV TLV tags */
  emvEncryptedData: EmvEncryptedData;
  /** Security code usually associated with a debit card. */
  pinData?: PinData;
  /** Provides more information about why the EMV Input Mode was used. */
  cardInputCode: EmvCardInputCode;
  /** EMV Kernel version of the device. */
  kernelVersion?: string;
}

export const emvInstrumentEncryptedSchema: Schema<EmvInstrumentEncrypted> = object(
  {
    type: ['type', string()],
    emvTlvData: ['emvTlvData', string()],
    emvEncryptedData: ['emvEncryptedData', lazy(() => emvEncryptedDataSchema)],
    pinData: ['pinData', optional(lazy(() => pinDataSchema))],
    cardInputCode: ['cardInputCode', emvCardInputCodeSchema],
    kernelVersion: ['kernelVersion', optional(string())],
  }
);
