/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  EmvCardInputCode,
  emvCardInputCodeSchema,
} from './emvCardInputCode.js';
import { PinData, pinDataSchema } from './pinData.js';

/** EMV instrument for clear card data */
export interface EmvInstrumentClear {
  /** Value indicating the specific type instance for this field. */
  type: string;
  emvTlvData: string;
  track2EquivalentData: string;
  /** Security code usually associated with a debit card. */
  pinData?: PinData;
  /** Provides more information about why the EMV Input Mode was used. */
  cardInputCode: EmvCardInputCode;
  /** EMV Kernel version of the device. */
  kernelVersion?: string;
}

export const emvInstrumentClearSchema: Schema<EmvInstrumentClear> = object({
  type: ['type', string()],
  emvTlvData: ['emvTlvData', string()],
  track2EquivalentData: ['track2EquivalentData', string()],
  pinData: ['pinData', optional(lazy(() => pinDataSchema))],
  cardInputCode: ['cardInputCode', emvCardInputCodeSchema],
  kernelVersion: ['kernelVersion', optional(string())],
});
