/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Issuer specific data returned for an EMV transaction. */
export interface EmvResponse {
  issuerAuthenticationData?: string;
  issuerScriptData?: string;
}

export const emvResponseSchema: Schema<EmvResponse> = object({
  issuerAuthenticationData: ['issuerAuthenticationData', optional(string())],
  issuerScriptData: ['issuerScriptData', optional(string())],
});
