/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  PlainCardDataEncrypted,
  plainCardDataEncryptedSchema,
} from './plainCardDataEncrypted.js';

/** Encrypted Information about the card being used. */
export interface EncryptedKeyedInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Encrypted Information about the card being used. */
  encryptedCardData: PlainCardDataEncrypted;
}

export const encryptedKeyedInstrumentSchema: Schema<EncryptedKeyedInstrument> = object(
  {
    type: ['type', string()],
    encryptedCardData: [
      'encryptedCardData',
      lazy(() => plainCardDataEncryptedSchema),
    ],
  }
);
