/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import { CountryCode, countryCodeSchema } from './countryCode.js';
import { Level3LineItem, level3LineItemSchema } from './level3LineItem.js';

/** Data associated with Level 3 interchange. */
export interface EnhancedDataLevel3 {
  type: string;
  /** User-defined commercial card customer code, such as a PO Number. */
  commercialCardCustomerCode: string;
  /** International description code of overall goods or services. */
  summaryCommodityCode: string;
  /** Postal/Zip Code of the address from where the purchased goods are being shipped. */
  shipFromPostalCode: string;
  /** Supported ISO 3166-1 alpha-2 country code. */
  destinationCountryCode: CountryCode;
  /** Purchase order date, conforming to the ISO-8601 specification. */
  orderDate: string;
  lineItems?: Level3LineItem[];
}

export const enhancedDataLevel3Schema: Schema<EnhancedDataLevel3> = object({
  type: ['type', string()],
  commercialCardCustomerCode: ['commercialCardCustomerCode', string()],
  summaryCommodityCode: ['summaryCommodityCode', string()],
  shipFromPostalCode: ['shipFromPostalCode', string()],
  destinationCountryCode: ['destinationCountryCode', countryCodeSchema],
  orderDate: ['orderDate', string()],
  lineItems: ['lineItems', optional(array(lazy(() => level3LineItemSchema)))],
});
