/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Data associated with Level 2 interchange.  Other payment fields should always be provided for Level 2. | Sales Tax Amount, Shipping Address Zip Code, and Billing Address First/Last Name. */
export interface EnhancedDataLevel2 {
  type: string;
  /** User-defined commercial card customer code, such as a PO Number. */
  commercialCardCustomerCode: string;
}

export const enhancedDataLevel2Schema: Schema<EnhancedDataLevel2> = object({
  type: ['type', string()],
  commercialCardCustomerCode: ['commercialCardCustomerCode', string()],
});
