/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema } from '../schema.js';

/** Information about the expiration date. */
export interface Expiration {
  /** Calendar month of expiration. */
  month: number;
  /** Calendar year of expiration. */
  year: number;
}

export const expirationSchema: Schema<Expiration> = object({
  month: ['month', number()],
  year: ['year', number()],
});
