/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** 3DS authentication using separate provider (External MPI). */
export interface ExternalProvider {
  type: string;
  version?: string;
  authenticationValue?: string;
  eci?: string;
  transactionId?: string;
  additionalProperties?: Record<string, unknown>;
}

export const externalProviderSchema: Schema<ExternalProvider> = typedExpandoObject(
  {
    type: ['type', string()],
    version: ['version', optional(string())],
    authenticationValue: ['authenticationValue', optional(string())],
    eci: ['eci', optional(string())],
    transactionId: ['transactionId', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
