/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, optional, Schema, string } from '../schema.js';

/** This object contains customer data for the Fleet transaction. */
export interface FleetCustomer {
  /** Fleet Vehicle Number. */
  vehicleNumber?: string;
  /** Fleet Driver Number. */
  driverNumber?: string;
  /** Fleet Driver Id Number. */
  driverIdNumber?: string;
  /** Vehicle Odometer reading. */
  odometerReading?: bigint;
}

export const fleetCustomerSchema: Schema<FleetCustomer> = object({
  vehicleNumber: ['vehicleNumber', optional(string())],
  driverNumber: ['driverNumber', optional(string())],
  driverIdNumber: ['driverIdNumber', optional(string())],
  odometerReading: ['odometerReading', optional(bigint())],
});
