/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, numberEnum } from '../schema.js';

/**
 * Enum for FleetRestrictionIndicator
 */
export enum FleetRestrictionIndicator {
  Enum1 = 1,
  Enum2 = 2,
  Enum3 = 3,
}

/**
 * Schema for FleetRestrictionIndicator
 */
export const fleetRestrictionIndicatorSchema: Schema<FleetRestrictionIndicator> = numberEnum(
  FleetRestrictionIndicator
);
