/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for FleetServiceType
 */
export enum FleetServiceType {
  S = 'S',
  F = 'F',
  O = 'O',
  N = 'N',
  X = 'X',
}

/**
 * Schema for FleetServiceType
 */
export const fleetServiceTypeSchema: Schema<FleetServiceType> = stringEnum(
  FleetServiceType
);
