/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema } from '../schema.js';

/** Results of an optional Fraud Check. */
export interface FraudResult {
  /**
   * If requested, the current risk status from Merchant Fraudsight will be returned.
   * <br>
   *   **Possible Values:**
   *   | Value | Description |
   *   | ----- | ------------|
   *   | 0 | Pass |
   *   | 1 | Review |
   *   | 2 | Fail |
   *   | 3 | Unknown |
   *   | 4 | Fail, informational only: Transaction approved |
   */
  riskStatus?: number;
  /** If requested, the current risk score from Merchant Fraudsight will be returned where the risk score is between 0.0000 and 1.0000. */
  riskScore?: number;
}

export const fraudResultSchema: Schema<FraudResult> = object({
  riskStatus: ['riskStatus', optional(number())],
  riskScore: ['riskScore', optional(number())],
});
