/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MerchantAuth, merchantAuthSchema } from './merchantAuth.js';
import { OperatingSystem, operatingSystemSchema } from './operatingSystem.js';

/** Obtains a payment card reader token, used for SoftPOS payments, along with all relevant entitlements */
export interface GetClientPcrtRequest {
  /** Identifying information associated with the Merchant submitting the request. */
  merchant: MerchantAuth;
  /** Identifier associated with the client's configured SoftPOS terminal profile. */
  terminalProfileId?: string;
  /** Name of the merchant to display on the device. This parameter is optional. */
  merchantBannerName?: string;
  /** Identifiers for the permitted application bundles. */
  allowedApplicationBundleIds?: string[];
  /** Number of seconds after which the payment card reader token should expire. The default value is 120 seconds. */
  tokenTimeToLiveSeconds?: bigint;
  /** Name of the operating system of the device requesting access to the proximity reader. */
  operatingSystem: OperatingSystem;
  additionalProperties?: Record<string, unknown>;
}

export const getClientPcrtRequestSchema: Schema<GetClientPcrtRequest> = typedExpandoObject(
  {
    merchant: ['merchant', lazy(() => merchantAuthSchema)],
    terminalProfileId: ['terminalProfileId', optional(string())],
    merchantBannerName: ['merchantBannerName', optional(string())],
    allowedApplicationBundleIds: [
      'allowedApplicationBundleIds',
      optional(array(string())),
    ],
    tokenTimeToLiveSeconds: ['tokenTimeToLiveSeconds', optional(bigint())],
    operatingSystem: ['operatingSystem', operatingSystemSchema],
  },
  'additionalProperties',
  optional(unknown())
);
