/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Response payload with payment card reader token, used for SoftPOS payments, along with all relevant entitlements. */
export interface GetClientPcrtResponse {
  /** Date and time that the transaction was received and processed. This value conforms to the ISO-8601 specification. */
  dateTime: string;
  /** Base64-encoded token for the payment card reader. */
  token: string;
  additionalProperties?: Record<string, unknown>;
}

export const getClientPcrtResponseSchema: Schema<GetClientPcrtResponse> = typedExpandoObject(
  { dateTime: ['dateTime', string()], token: ['token', string()] },
  'additionalProperties',
  optional(unknown())
);
