/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { MerchantCapture, merchantCaptureSchema } from './merchantCapture.js';

/** Extend the authorization by this amount. */
export interface IncrementalAuthorizationRequest {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Identifying information associated with the Merchant submitting the request. */
  merchant?: MerchantCapture;
  /** Amount value in minor currency units with no decimal point. For example, $1.00 would be written as 100. */
  amount?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const incrementalAuthorizationRequestSchema: Schema<IncrementalAuthorizationRequest> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    merchant: ['merchant', optional(lazy(() => merchantCaptureSchema))],
    amount: ['amount', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
