/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Actions, actionsSchema } from './actions.js';

export interface IncrementalAuthResponseActions {
  /** HATEOAS links for response payloads. */
  cancelPayment?: Actions;
  /** HATEOAS links for response payloads. */
  capturePayment?: Actions;
  additionalProperties?: Record<string, unknown>;
}

export const incrementalAuthResponseActionsSchema: Schema<IncrementalAuthResponseActions> = typedExpandoObject(
  {
    cancelPayment: ['cancelPayment', optional(lazy(() => actionsSchema))],
    capturePayment: ['capturePayment', optional(lazy(() => actionsSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
