/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Usage3, usage3Schema } from './usage3.js';

/** Polymorphic reference for installment data */
export interface Installment {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /**
   * Setup an __Installment__ agreement for the following cases... <br> <ul>
   *   <li> (__first__) - The __first__ time this card is being presented, and being stored by the Merchant for the purposes of a __Subscription__. </li>
   *   <li> (__subsequent__) - Used when the Merchant is managing the __Subscription__. </li>
   *   <li> (__resubmission__) - Resubmit a previously declined payment. The card holder may have resolved the reason for the original decline, i.e. lack of funds, etc., thus the Payment can be resubmitted. </li>
   * </ul>
   */
  usage: Usage3;
  /**
   * Unique scheme reference for a repeat agreement between you and the customer. <br>
   * New reference is generated for each subsequent payment. Most but __not all__ issuers return this. <br>
   * Included in the Worldpay Token if created with the initial agreement (first) and therefore not required here.
   */
  schemeReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const installmentSchema: Schema<Installment> = typedExpandoObject(
  {
    type: ['type', string()],
    usage: ['usage', usage3Schema],
    schemeReference: ['schemeReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
