/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for KeyedOrSwipedEncryptedFormat
 */
export enum KeyedOrSwipedEncryptedFormat {
  MagtekEmulated = 'magtekEmulated',
  Equinox = 'equinox',
  IdTechNative = 'idTechNative',
  VerifoneMx = 'verifoneMx',
  IngenicoRba = 'ingenicoRba',
  BbPosChipper = 'bbPosChipper',
  VerifoneVxLegacy = 'verifoneVxLegacy',
  VerifoneVxXpi = 'verifoneVxXpi',
  IgnenicoTetraOnguardSde = 'ignenicoTetraOnguardSde',
  IngenicoTetraGeneric = 'ingenicoTetraGeneric',
  GenericDukptData = 'genericDukptData',
  IngenicoOnGuardFpe = 'ingenicoOnGuardFPE',
  VerifoneVxVipa = 'verifoneVxVipa',
}

/**
 * Schema for KeyedOrSwipedEncryptedFormat
 */
export const keyedOrSwipedEncryptedFormatSchema: Schema<KeyedOrSwipedEncryptedFormat> = stringEnum(
  KeyedOrSwipedEncryptedFormat
);
