/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  PlainCardDataClear,
  plainCardDataClearSchema,
} from './plainCardDataClear.js';

/** Unencrypted Information about the card being used. */
export interface KeyedClearInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Unencrypted Information about the card being used. */
  cardData: PlainCardDataClear;
}

export const keyedClearInstrumentSchema: Schema<KeyedClearInstrument> = object({
  type: ['type', string()],
  cardData: ['cardData', lazy(() => plainCardDataClearSchema)],
});
