/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for KeyedFallbackReasonCode
 */
export enum KeyedFallbackReasonCode {
  ManualKeyedMagstripeFailure = 'manualKeyedMagstripeFailure',
  ManualKeyedChipReadFailure = 'manualKeyedChipReadFailure',
}

/**
 * Schema for KeyedFallbackReasonCode
 */
export const keyedFallbackReasonCodeSchema: Schema<KeyedFallbackReasonCode> = stringEnum(
  KeyedFallbackReasonCode
);
