/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, object, Schema, string } from '../schema.js';

/** This object contains line item detail for Level 3 interchange. */
export interface Level3LineItem {
  /** International description code of the individual good or service being supplied. | Recommend using national or international list of standardized codes. */
  commodityCode: string;
  /** Item description. */
  description: string;
  /** Merchant-defined description code of the item. */
  productCode: string;
  /** Quantity of the item (up to four decimal places). NNNNNNN.DDDD */
  quantity: string;
  /** Code for units of measurement used in international trade. */
  unitOfMeasure: string;
  /** Amount value in minor currency units with no decimal point. For example, $1.00 would be written as 100. */
  unitCost: bigint;
  /** Amount value in minor currency units with no decimal point. For example, $1.00 would be written as 100. */
  totalAmount: bigint;
}

export const level3LineItemSchema: Schema<Level3LineItem> = object({
  commodityCode: ['commodityCode', string()],
  description: ['description', string()],
  productCode: ['productCode', string()],
  quantity: ['quantity', string()],
  unitOfMeasure: ['unitOfMeasure', string()],
  unitCost: ['unitCost', bigint()],
  totalAmount: ['totalAmount', bigint()],
});
