/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, optional, Schema, typedExpandoObject } from '../schema.js';
import {
  LinksAdditionalFields,
  linksAdditionalFieldsSchema,
} from './linksAdditionalFields.js';
import { Self, selfSchema } from './self.js';

/** HATEOAS links for response payloads. */
export interface Links {
  self?: Self;
  additionalProperties?: Record<string, LinksAdditionalFields>;
}

export const linksSchema: Schema<Links> = typedExpandoObject(
  { self: ['self', optional(lazy(() => selfSchema))] },
  'additionalProperties',
  linksAdditionalFieldsSchema
);
