/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

export interface LinksAdditionalFields {
  /** URI to a static resource. */
  href?: string;
  additionalProperties?: Record<string, unknown>;
}

export const linksAdditionalFieldsSchema: Schema<LinksAdditionalFields> = typedExpandoObject(
  { href: ['href', optional(string())] },
  'additionalProperties',
  optional(unknown())
);
