/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Identifying information associated with the Merchant submitting the request. */
export interface MerchantAuth {
  /** Unique merchant account identifier assigned by Worldpay. */
  id?: string;
  /**
   * The Merchants reference to their business discriminator. Used to route the request
   * to how the Merchant has been boarded in Worldpay.
   */
  entity?: string;
  /** Needs a description, always required for Express, determines the batch. */
  terminalId?: string;
  /**
   * You can apply a merchant category code (mcc) to an individual request.
   * You can only provide an mcc if we have enabled the dynamic mcc feature during boarding.
   * If enabled but not provided, merchant.mcc defaults to a configured value.
   */
  mcc?: string;
}

export const merchantAuthSchema: Schema<MerchantAuth> = object({
  id: ['id', optional(string())],
  entity: ['entity', optional(string())],
  terminalId: ['terminalId', optional(string())],
  mcc: ['mcc', optional(string())],
});
