/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Identifying information associated with the Merchant submitting the request. */
export interface MerchantCapture {
  /** Unique merchant account identifier assigned by Worldpay. */
  id?: string;
  /** Identifier of the terminal; this value is always required for Express and determines the batch. */
  terminalId?: string;
}

export const merchantCaptureSchema: Schema<MerchantCapture> = object({
  id: ['id', optional(string())],
  terminalId: ['terminalId', optional(string())],
});
