/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Subsequent request merchant object. */
export interface MerchantSubsequentRequest {
  /** Unique merchant account identifier assigned by Worldpay. */
  id?: string;
  terminalId?: string;
}

export const merchantSubsequentRequestSchema: Schema<MerchantSubsequentRequest> = object(
  {
    id: ['id', optional(string())],
    terminalId: ['terminalId', optional(string())],
  }
);
