/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MotoCardPaymentMethodCreatePayment,
  motoCardPaymentMethodCreatePaymentSchema,
} from './motoCardPaymentMethodCreatePayment.js';
import { MotoDevice, motoDeviceSchema } from './motoDevice.js';

/** MOTO channel */
export interface MotoChannelCreatePayment {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** MOTO Payment Methods for authorizations */
  paymentMethod: MotoCardPaymentMethodCreatePayment;
  /** Information about the device used to accept the payment */
  device?: MotoDevice;
  additionalProperties?: Record<string, unknown>;
}

export const motoChannelCreatePaymentSchema: Schema<MotoChannelCreatePayment> = typedExpandoObject(
  {
    type: ['type', string()],
    paymentMethod: [
      'paymentMethod',
      lazy(() => motoCardPaymentMethodCreatePaymentSchema),
    ],
    device: ['device', optional(lazy(() => motoDeviceSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
