/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MotoCardInstruments,
  motoCardInstrumentsSchema,
} from './containers/motoCardInstruments.js';
import { TokenCreate, tokenCreateSchema } from './containers/tokenCreate.js';

/** MOTO Card Payment Method for refunds */
export interface MotoCardPaymentMethodRefund {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped, Inserted or Tapped) the customer is providing the card information. */
  instrument: MotoCardInstruments;
  /** Create a token for use in future payments */
  createToken?: TokenCreate;
  additionalProperties?: Record<string, unknown>;
}

export const motoCardPaymentMethodRefundSchema: Schema<MotoCardPaymentMethodRefund> = typedExpandoObject(
  {
    type: ['type', string()],
    instrument: ['instrument', motoCardInstrumentsSchema],
    createToken: ['createToken', optional(tokenCreateSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
