/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Information about the device used to accept the payment */
export interface MotoDevice {
  /** Lane/Register Number */
  laneNumber?: string;
  /** Serial Number (S/N) of the device/terminal. */
  serialNumber?: string;
  /** Model number of the device/terminal. */
  model?: string;
}

export const motoDeviceSchema: Schema<MotoDevice> = object({
  laneNumber: ['laneNumber', optional(string())],
  serialNumber: ['serialNumber', optional(string())],
  model: ['model', optional(string())],
});
