/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MotoCardPaymentMethodRefund,
  motoCardPaymentMethodRefundSchema,
} from './motoCardPaymentMethodRefund.js';
import { MotoDevice, motoDeviceSchema } from './motoDevice.js';

/** MOTO Channel (Refund) */
export interface MotoChannelRefund {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** MOTO Payment Methods */
  paymentMethod: MotoCardPaymentMethodRefund;
  /** Information about the device used to accept the payment */
  device?: MotoDevice;
  additionalProperties?: Record<string, unknown>;
}

export const motoChannelRefundSchema: Schema<MotoChannelRefund> = typedExpandoObject(
  {
    type: ['type', string()],
    paymentMethod: [
      'paymentMethod',
      lazy(() => motoCardPaymentMethodRefundSchema),
    ],
    device: ['device', optional(lazy(() => motoDeviceSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
