/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Unaltered response data from the downstream acquirer or issuer. */
export interface NetworkResponsePaymentRetrieval {
  /** Issuer approval code */
  approvalCode?: string;
  /** Response code from downstream acquirer. */
  acquirerResponseCode?: string;
  /** Response code from card issuer. */
  issuerResponseCode?: string;
  /** Scheme reference used for Credentials on File. */
  schemeReference?: string;
  /** Mastercard only. */
  adviceCode?: string;
  /** issuer response for AVS Check <br> **Possible Values:** | Value | Description | | ----- | ------------| | A | Address Matches, ZIP does not | | B | Address Matches, ZIP not verified | | C | Address an ZIP not verified | | D | Address and postal code match, international AVS only | | E | Edit Error or ineligible | | F | Address and ZIP match - UK only | | G | Address not verified - international | | I | Address not verified | | M | Address and postal code match, international AVS only | | N | Neither address nor ZIP match | | P | Codes match, addresses not verified | | R | System unavailable or time-out | | S | AVS not supported | | U | Address info N/A | | W | Nine digit zip matches, not address | | X | Address and nine digit zip match, domestic AVS only | | Y | Address and five digit zip match, domestic AVS only | | Z | ZIP matches, address does not | */
  avsResult?: string;
  /** issuer response for CVC */
  cvcResult?: string;
  additionalProperties?: Record<string, unknown>;
}

export const networkResponsePaymentRetrievalSchema: Schema<NetworkResponsePaymentRetrieval> = typedExpandoObject(
  {
    approvalCode: ['approvalCode', optional(string())],
    acquirerResponseCode: ['acquirerResponseCode', optional(string())],
    issuerResponseCode: ['issuerResponseCode', optional(string())],
    schemeReference: ['schemeReference', optional(string())],
    adviceCode: ['adviceCode', optional(string())],
    avsResult: ['avsResult', optional(string())],
    cvcResult: ['cvcResult', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
