/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Unaltered response data from the downstream acquirer or issuer. */
export interface NetworkResponseReferencedFollowOn {
  /** Issuer approval code. */
  approvalCode?: string;
  /** Response code from downstream acquirer. */
  acquirerResponseCode?: string;
  /** Response code from card issuer. */
  issuerResponseCode?: string;
  /** Scheme reference used for Credentials on File. */
  schemeReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const networkResponseReferencedFollowOnSchema: Schema<NetworkResponseReferencedFollowOn> = typedExpandoObject(
  {
    approvalCode: ['approvalCode', optional(string())],
    acquirerResponseCode: ['acquirerResponseCode', optional(string())],
    issuerResponseCode: ['issuerResponseCode', optional(string())],
    schemeReference: ['schemeReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
