/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Not found error */
export interface NotFoundError {
  /** High-level classification for the error. */
  title: string;
  /** Resource identifier (e.g., payment ID) on which the caller attempted to interact but was deemed invalid. */
  resourceId?: string;
  /** Human-readable description of the non-found error. */
  message?: string;
}

export const notFoundErrorSchema: Schema<NotFoundError> = object({
  title: ['title', string()],
  resourceId: ['resourceId', optional(string())],
  message: ['message', optional(string())],
});
