/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for OperatingSystem
 */
export enum OperatingSystem {
  Ios = 'iOS',
  Android = 'android',
}

/**
 * Schema for OperatingSystem
 */
export const operatingSystemSchema: Schema<OperatingSystem> = stringEnum(
  OperatingSystem
);
