/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Express PASS token instrument */
export interface PassToken {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Globally unique identifier. */
  token: string;
  additionalProperties?: Record<string, unknown>;
}

export const passTokenSchema: Schema<PassToken> = typedExpandoObject(
  { type: ['type', string()], token: ['token', string()] },
  'additionalProperties',
  optional(unknown())
);
