/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, optional, Schema } from '../schema.js';

/** Options for handling the authorization request */
export interface PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods {
  /** If true, you want to perform an address verification. */
  addressVerification?: boolean;
  /** If true, you will accept approvals for less than the total requested amount. */
  partialApproval?: boolean;
}

export const paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema: Schema<PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods> = object(
  {
    addressVerification: ['addressVerification', optional(boolean())],
    partialApproval: ['partialApproval', optional(boolean())],
  }
);
