/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Scheduled payment response payload */
export interface PaymentResultScheduledPayment {
  /**
   * Outcome of the payment task; one of the following values:
   *   authorized, refused
   */
  outcome: string;
  /** Globally unique identifer defined by Worldpay. */
  id?: string;
  /** Reference number supplied with the initial payment request from which this scheduled task was created. */
  reference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentResultScheduledPaymentSchema: Schema<PaymentResultScheduledPayment> = typedExpandoObject(
  {
    outcome: ['outcome', string()],
    id: ['id', optional(string())],
    reference: ['reference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
