/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Response data specific to the payment method. */
export interface PaymentMethodResponseUnreferencedRefund {
  type: string;
  additionalProperties?: Record<string, unknown>;
}

export const paymentMethodResponseUnreferencedRefundSchema: Schema<PaymentMethodResponseUnreferencedRefund> = typedExpandoObject(
  { type: ['type', string()] },
  'additionalProperties',
  optional(unknown())
);
