/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Phone number. */
export interface Phone {
  code?: string;
  number?: string;
  additionalProperties?: Record<string, unknown>;
}

export const phoneSchema: Schema<Phone> = typedExpandoObject(
  {
    code: ['code', optional(string())],
    number: ['number', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
