/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Security code usually associated with a debit card. */
export interface PinData {
  /** Data used to encapsulate a PIN during processing. */
  pinBlock: string;
  /** Serial number of the key. */
  keySerialNumber: string;
}

export const pinDataSchema: Schema<PinData> = object({
  pinBlock: ['pinBlock', string()],
  keySerialNumber: ['keySerialNumber', string()],
});
