/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CardExpiration, cardExpirationSchema } from './cardExpiration.js';

/** Unencrypted Information about the card being used. */
export interface PlainGiftCardDataClear {
  /** Primary Account Number (PAN) on the card. */
  cardNumber: string;
  /** Information about the expiration date for the card. */
  expiryDate: CardExpiration;
  /** CVV value or a Gift Card Security Code. */
  securityCode?: string;
  additionalProperties?: Record<string, unknown>;
}

export const plainGiftCardDataClearSchema: Schema<PlainGiftCardDataClear> = typedExpandoObject(
  {
    cardNumber: ['cardNumber', string()],
    expiryDate: ['expiryDate', lazy(() => cardExpirationSchema)],
    securityCode: ['securityCode', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
