/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CardExpiration, cardExpirationSchema } from './cardExpiration.js';

/** Unencrypted Information about the card being used. */
export interface PlainCardDataClear {
  /** Primary Account Number (PAN) on the card. */
  cardNumber: string;
  /** Information about the expiration date for the card. */
  expiryDate: CardExpiration;
  /** Card verification code (CVC). Also known as Card Verification Value (CVV) */
  cvc?: string;
  additionalProperties?: Record<string, unknown>;
}

export const plainCardDataClearSchema: Schema<PlainCardDataClear> = typedExpandoObject(
  {
    cardNumber: ['cardNumber', string()],
    expiryDate: ['expiryDate', lazy(() => cardExpirationSchema)],
    cvc: ['cvc', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
