/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';
import {
  KeyedOrSwipedEncryptedFormat,
  keyedOrSwipedEncryptedFormatSchema,
} from './keyedOrSwipedEncryptedFormat.js';

/** Encrypted Information about the card being used. */
export interface PlainCardDataEncrypted {
  keySerialNumber: string;
  /** Device manufacturer and family-specific encryption format for card present transactions */
  encryptedFormat: KeyedOrSwipedEncryptedFormat;
  encryptedData: string;
}

export const plainCardDataEncryptedSchema: Schema<PlainCardDataEncrypted> = object(
  {
    keySerialNumber: ['keySerialNumber', string()],
    encryptedFormat: ['encryptedFormat', keyedOrSwipedEncryptedFormatSchema],
    encryptedData: ['encryptedData', string()],
  }
);
