/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  PlainGiftCardDataClear,
  plainGiftCardDataClearSchema,
} from './plainGiftCardDataClear.js';

/** Unencrypted Information about the card being used. */
export interface PlainGiftCardDataInstrumentClear {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Unencrypted Information about the card being used. */
  cardData: PlainGiftCardDataClear;
}

export const plainGiftCardDataInstrumentClearSchema: Schema<PlainGiftCardDataInstrumentClear> = object(
  {
    type: ['type', string()],
    cardData: ['cardData', lazy(() => plainGiftCardDataClearSchema)],
  }
);
