/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  PosPaymentMethodsAuth,
  posPaymentMethodsAuthSchema,
} from './containers/posPaymentMethodsAuth.js';
import { PosDevice, posDeviceSchema } from './posDevice.js';

/** This type of transaction takes place when the Card is present and either swiped, keyed, inserted into or tapped on the terminal. */
export interface PosChannelCreatePayment {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies what the customer is using to pay with */
  paymentMethod: PosPaymentMethodsAuth;
  /** An identifier when a payment is accepted on a Soft POS-capable mobile device/smartphone, regardless of whether or not the payment was contactless. */
  softPosId?: string;
  /** Information about the device used to accept the payment */
  device?: PosDevice;
  /** Allows integrator to track employee accepting this payment. */
  clerkId?: string;
  /** Allows integrator to associate this payment with an employee shift. */
  shiftId?: string;
}

export const posChannelCreatePaymentSchema: Schema<PosChannelCreatePayment> = object(
  {
    type: ['type', string()],
    paymentMethod: ['paymentMethod', posPaymentMethodsAuthSchema],
    softPosId: ['softPosId', optional(string())],
    device: ['device', optional(lazy(() => posDeviceSchema))],
    clerkId: ['clerkId', optional(string())],
    shiftId: ['shiftId', optional(string())],
  }
);
