/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  CardPaymentMethodOptionsRefund,
  cardPaymentMethodOptionsRefundSchema,
} from './cardPaymentMethodOptionsRefund.js';
import {
  PosCardInstruments,
  posCardInstrumentsSchema,
} from './containers/posCardInstruments.js';
import { TokenCreate, tokenCreateSchema } from './containers/tokenCreate.js';

/** Payment method for POS, specific to refunds. */
export interface PosCardPaymentMethodRefund {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped, Inserted or Tapped) the customer is providing the card information. */
  instrument: PosCardInstruments;
  /** Options for handling the authorization request. */
  options?: CardPaymentMethodOptionsRefund;
  /** Create a token for use in future payments */
  createToken?: TokenCreate;
}

export const posCardPaymentMethodRefundSchema: Schema<PosCardPaymentMethodRefund> = object(
  {
    type: ['type', string()],
    instrument: ['instrument', posCardInstrumentsSchema],
    options: [
      'options',
      optional(lazy(() => cardPaymentMethodOptionsRefundSchema)),
    ],
    createToken: ['createToken', optional(tokenCreateSchema)],
  }
);
