/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AdditionalAmountsCreditCardPresent,
  additionalAmountsCreditCardPresentSchema,
} from './additionalAmountsCreditCardPresent.js';
import {
  CardPaymentMethodOptions,
  cardPaymentMethodOptionsSchema,
} from './cardPaymentMethodOptions.js';
import {
  CustomerAgreement,
  customerAgreementSchema,
} from './containers/customerAgreement.js';
import {
  PosCardInstruments,
  posCardInstrumentsSchema,
} from './containers/posCardInstruments.js';
import { Threeds, threedsSchema } from './containers/threeds.js';
import { TokenCreate, tokenCreateSchema } from './containers/tokenCreate.js';

/** Payment method for POS */
export interface PosCardPaymentMethodCreatePayment {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped, Inserted or Tapped) the customer is providing the card information. */
  instrument: PosCardInstruments;
  /** Other (optional) amounts that are included in the Total Authorization Amount, for credit card present */
  otherAmounts?: AdditionalAmountsCreditCardPresent;
  /** Options for handling the authorization request */
  options?: CardPaymentMethodOptions;
  /** Create a token for use in future payments */
  createToken?: TokenCreate;
  /** An object containing 3DS authentication preferences and customer data */
  threeDs?: Threeds;
  /** Setup an initial agreement (__first__) to store a customers payment details and make __subsequent__  payments when __storing a card__, for __subscriptions__, __installments__, __scheduled__, and __unscheduled__ payments */
  customerAgreement?: CustomerAgreement;
}

export const posCardPaymentMethodCreatePaymentSchema: Schema<PosCardPaymentMethodCreatePayment> = object(
  {
    type: ['type', string()],
    instrument: ['instrument', posCardInstrumentsSchema],
    otherAmounts: [
      'otherAmounts',
      optional(lazy(() => additionalAmountsCreditCardPresentSchema)),
    ],
    options: ['options', optional(lazy(() => cardPaymentMethodOptionsSchema))],
    createToken: ['createToken', optional(tokenCreateSchema)],
    threeDs: ['threeDs', optional(threedsSchema)],
    customerAgreement: ['customerAgreement', optional(customerAgreementSchema)],
  }
);
