/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  DeviceCapabilities,
  deviceCapabilitiesSchema,
} from './deviceCapabilities.js';
import {
  DeviceEnvironment,
  deviceEnvironmentSchema,
} from './deviceEnvironment.js';

/** Information about the device used to accept the payment */
export interface PosDevice {
  /** Lane/Register Number */
  laneNumber?: string;
  /** Serial Number (S/N) of the device/terminal. */
  serialNumber?: string;
  /** Model number of the device/terminal. */
  model?: string;
  /** Indicates information the card read capabilities of the device */
  capabilities?: DeviceCapabilities;
  /** Environment in which the payment is being accepted. */
  environment?: DeviceEnvironment;
}

export const posDeviceSchema: Schema<PosDevice> = object({
  laneNumber: ['laneNumber', optional(string())],
  serialNumber: ['serialNumber', optional(string())],
  model: ['model', optional(string())],
  capabilities: ['capabilities', optional(deviceCapabilitiesSchema)],
  environment: ['environment', optional(deviceEnvironmentSchema)],
});
