/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AdditionalAmountsEbtEwic,
  additionalAmountsEbtEwicSchema,
} from './additionalAmountsEbtEwic.js';
import {
  PosEwicInstruments,
  posEwicInstrumentsSchema,
} from './containers/posEwicInstruments.js';
import {
  PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods,
  paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema,
} from './paymentMethodOptionsAssociatedWithNonCreditOrDebitMethods.js';

/** Information from the EWIC (electronic Woman Infants and Children) Card. */
export interface PosEwicPaymentMethod {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped) the customer is providing the card information. */
  instrument: PosEwicInstruments;
  /** Other (optional) amounts that are included in the Total Authorization Amount, for EBT and eWIC transactions */
  otherAmounts?: AdditionalAmountsEbtEwic;
  ewicMerchantId?: string;
  /** Options for handling the authorization request */
  options?: PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods;
}

export const posEwicPaymentMethodSchema: Schema<PosEwicPaymentMethod> = object({
  type: ['type', string()],
  instrument: ['instrument', posEwicInstrumentsSchema],
  otherAmounts: [
    'otherAmounts',
    optional(lazy(() => additionalAmountsEbtEwicSchema)),
  ],
  ewicMerchantId: ['ewicMerchantId', optional(string())],
  options: [
    'options',
    optional(
      lazy(
        () => paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema
      )
    ),
  ],
});
