/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, lazy, object, optional, Schema, string } from '../schema.js';
import {
  AdditionalAmountsEbtEwic,
  additionalAmountsEbtEwicSchema,
} from './additionalAmountsEbtEwic.js';
import {
  PosEbtInstruments,
  posEbtInstrumentsSchema,
} from './containers/posEbtInstruments.js';
import {
  PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods,
  paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema,
} from './paymentMethodOptionsAssociatedWithNonCreditOrDebitMethods.js';

/** Information from the EBT (Electronic Funds Transfer) Card. */
export interface PosEbtPaymentMethod {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped) the customer is providing the card information. */
  instrument: PosEbtInstruments;
  /** Other (optional) amounts that are included in the Total Authorization Amount, for EBT and eWIC transactions */
  otherAmounts?: AdditionalAmountsEbtEwic;
  voucher?: string;
  fnsNumber?: string;
  foodstampOnly?: boolean;
  /** Options for handling the authorization request */
  options?: PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods;
}

export const posEbtPaymentMethodSchema: Schema<PosEbtPaymentMethod> = object({
  type: ['type', string()],
  instrument: ['instrument', posEbtInstrumentsSchema],
  otherAmounts: [
    'otherAmounts',
    optional(lazy(() => additionalAmountsEbtEwicSchema)),
  ],
  voucher: ['voucher', optional(string())],
  fnsNumber: ['fnsNumber', optional(string())],
  foodstampOnly: ['foodstampOnly', optional(boolean())],
  options: [
    'options',
    optional(
      lazy(
        () => paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema
      )
    ),
  ],
});
