/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  KeyedFallbackReasonCode,
  keyedFallbackReasonCodeSchema,
} from './keyedFallbackReasonCode.js';
import { PinData, pinDataSchema } from './pinData.js';
import {
  PlainCardDataClear,
  plainCardDataClearSchema,
} from './plainCardDataClear.js';

/** Use either CardData or EncryptedCardData (when using P2PE) */
export interface PosKeyedClear {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Unencrypted Information about the card being used. */
  cardData: PlainCardDataClear;
  /** Security code usually associated with a debit card. */
  pinData?: PinData;
  /** Provides more information about why a lower capability entry mode was used. Do not supply if no EMV fallback occurred. */
  fallbackReasonCode?: KeyedFallbackReasonCode;
}

export const posKeyedClearSchema: Schema<PosKeyedClear> = object({
  type: ['type', string()],
  cardData: ['cardData', lazy(() => plainCardDataClearSchema)],
  pinData: ['pinData', optional(lazy(() => pinDataSchema))],
  fallbackReasonCode: [
    'fallbackReasonCode',
    optional(keyedFallbackReasonCodeSchema),
  ],
});
