/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  KeyedFallbackReasonCode,
  keyedFallbackReasonCodeSchema,
} from './keyedFallbackReasonCode.js';
import { PinData, pinDataSchema } from './pinData.js';
import {
  PlainCardDataEncrypted,
  plainCardDataEncryptedSchema,
} from './plainCardDataEncrypted.js';

/** Use either CardData or EncryptedCardData (when using P2PE) */
export interface PosKeyedEncrypted {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Encrypted Information about the card being used. */
  encryptedCardData: PlainCardDataEncrypted;
  /** Security code usually associated with a debit card. */
  pinData?: PinData;
  /** Provides more information about why a lower capability entry mode was used. Do not supply if no EMV fallback occurred. */
  fallbackReasonCode?: KeyedFallbackReasonCode;
}

export const posKeyedEncryptedSchema: Schema<PosKeyedEncrypted> = object({
  type: ['type', string()],
  encryptedCardData: [
    'encryptedCardData',
    lazy(() => plainCardDataEncryptedSchema),
  ],
  pinData: ['pinData', optional(lazy(() => pinDataSchema))],
  fallbackReasonCode: [
    'fallbackReasonCode',
    optional(keyedFallbackReasonCodeSchema),
  ],
});
