/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AdditionalAmountsCreditCardPresent,
  additionalAmountsCreditCardPresentSchema,
} from './additionalAmountsCreditCardPresent.js';
import {
  PosGiftInstruments,
  posGiftInstrumentsSchema,
} from './containers/posGiftInstruments.js';
import {
  PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods,
  paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema,
} from './paymentMethodOptionsAssociatedWithNonCreditOrDebitMethods.js';

/** Information from the Merchant Gift Card. */
export interface PosMerchantClosedLoopGiftCardPaymentMethodCreatePayment {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped) the customer is providing the card information. */
  instrument: PosGiftInstruments;
  /** Other (optional) amounts that are included in the Total Authorization Amount, for credit card present */
  otherAmounts?: AdditionalAmountsCreditCardPresent;
  /** Options for handling the authorization request */
  options?: PaymentMethodOptionsAssociatedWithNonCreditOrDebitMethods;
}

export const posMerchantClosedLoopGiftCardPaymentMethodCreatePaymentSchema: Schema<PosMerchantClosedLoopGiftCardPaymentMethodCreatePayment> = object(
  {
    type: ['type', string()],
    instrument: ['instrument', posGiftInstrumentsSchema],
    otherAmounts: [
      'otherAmounts',
      optional(lazy(() => additionalAmountsCreditCardPresentSchema)),
    ],
    options: [
      'options',
      optional(
        lazy(
          () => paymentMethodOptionsAssociatedWithNonCreditOrDebitMethodsSchema
        )
      ),
    ],
  }
);
