/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';
import {
  PosGiftInstruments,
  posGiftInstrumentsSchema,
} from './containers/posGiftInstruments.js';

/** Information from the merchant gift card. */
export interface PosMerchantClosedLoopGiftCardPaymentMethodRefund {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Identifies **HOW** (ex Keyed, Swiped) the customer is providing the card information. */
  instrument: PosGiftInstruments;
}

export const posMerchantClosedLoopGiftCardPaymentMethodRefundSchema: Schema<PosMerchantClosedLoopGiftCardPaymentMethodRefund> = object(
  {
    type: ['type', string()],
    instrument: ['instrument', posGiftInstrumentsSchema],
  }
);
