/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProcessAsEnum
 */
export enum ProcessAsEnum {
  CreditOrSignatureDebit = 'creditOrSignatureDebit',
  PinDebit = 'pinDebit',
}

/**
 * Schema for ProcessAsEnum
 */
export const processAsEnumSchema: Schema<ProcessAsEnum> = stringEnum(
  ProcessAsEnum
);
