/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProductType
 */
export enum ProductType {
  F = 'F',
  N = 'N',
}

/**
 * Schema for ProductType
 */
export const productTypeSchema: Schema<ProductType> = stringEnum(ProductType);
