/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  boolean,
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  ScheduledPaymentExecution,
  scheduledPaymentExecutionSchema,
} from './scheduledPaymentExecution.js';
import {
  ScheduledPaymentsRunInterval,
  scheduledPaymentsRunIntervalSchema,
} from './scheduledPaymentsRunInterval.js';

/** Response payload for scheduled payment query requests */
export interface QueryPaymentScheduleResponse {
  /** Date in YYYY-MM-DD format on which the payment (or initial, if multiple) will be or was run. */
  startDate: string;
  /** Next date in YYYY-MM-DD format on which the payment will be run (if applicable). */
  nextRunDate?: string;
  /** Total number of times the schedule is set to run, if interval is not set to oneTimeFuture. If __absent__, the schedule is set to run until explicitly deleted. */
  numberOfPayments?: number;
  /** Scheduled Payments Run interval */
  interval: ScheduledPaymentsRunInterval;
  /** Multiplier against which the interval will be assessed; example: when interval = monthly and multiplier = 3, the payment will be run every 3 months. */
  multiplier?: number;
  /** Returns true if any future runs of the schedule remain; otherwise, false */
  active: boolean;
  payments?: ScheduledPaymentExecution[];
  additionalProperties?: Record<string, unknown>;
}

export const queryPaymentScheduleResponseSchema: Schema<QueryPaymentScheduleResponse> = typedExpandoObject(
  {
    startDate: ['startDate', string()],
    nextRunDate: ['nextRunDate', optional(string())],
    numberOfPayments: ['numberOfPayments', optional(number())],
    interval: ['interval', scheduledPaymentsRunIntervalSchema],
    multiplier: ['multiplier', optional(number())],
    active: ['active', boolean()],
    payments: [
      'payments',
      optional(array(lazy(() => scheduledPaymentExecutionSchema))),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
