/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { bigint, boolean, object, optional, Schema } from '../schema.js';

/** Balances data for response payloads specific to referenced refunds; note that these balance values only reflect the specific refund and void refund operations - they will not be decremented by operations such as cancellations. For a complete picture of the payment lifecycle, perform a retrieval on the payment resource itself. */
export interface ReferencedRefundBalances {
  /** Total amount requested for refund for this payment in minor currency units with no decimal point. For example, $1.00 USD would be written as 100. */
  requested?: bigint;
  /** Total amount refunded for this payment (minus any voids) in minor currency units **with no decimal point**. For example, $1.00 USD would be written as 100. */
  current?: bigint;
  /** Total amount currently available for refund on this payment. For example, $1.00 USD would be written as 100. */
  available?: bigint;
  /** Voided indictor - true if this capture sub-resource has been voided */
  voided?: boolean;
}

export const referencedRefundBalancesSchema: Schema<ReferencedRefundBalances> = object(
  {
    requested: ['requested', optional(bigint())],
    current: ['current', optional(bigint())],
    available: ['available', optional(bigint())],
    voided: ['voided', optional(boolean())],
  }
);
