/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AmountWithCurrency,
  amountWithCurrencySchema,
} from './amountWithCurrency.js';
import {
  UnreferencedRefundChannels,
  unreferencedRefundChannelsSchema,
} from './containers/unreferencedRefundChannels.js';
import { MerchantAuth, merchantAuthSchema } from './merchantAuth.js';

/** Credit funds to a cardholder's account, without referencing a previous payment */
export interface RefundRequestUnreferenced {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Identifying information associated with the Merchant submitting the request. */
  merchant?: MerchantAuth;
  /** The Total Amount including currency (and optionally a breakdown) associated with this payment or follow-on request */
  amount?: AmountWithCurrency;
  /** Object group for refund-specific channels */
  channel: UnreferencedRefundChannels;
  additionalProperties?: Record<string, unknown>;
}

export const refundRequestUnreferencedSchema: Schema<RefundRequestUnreferenced> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    merchant: ['merchant', optional(lazy(() => merchantAuthSchema))],
    amount: ['amount', optional(lazy(() => amountWithCurrencySchema))],
    channel: ['channel', unreferencedRefundChannelsSchema],
  },
  'additionalProperties',
  optional(unknown())
);
