/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  bigint,
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MerchantSubsequentRequest,
  merchantSubsequentRequestSchema,
} from './merchantSubsequentRequest.js';

/** Refund a specific payment. */
export interface RefundRequestReferenced {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Subsequent request merchant object. */
  merchant?: MerchantSubsequentRequest;
  /** Amount value in minor currency units with no decimal point. For example, $1.00 would be written as 100. */
  amount?: bigint;
  additionalProperties?: Record<string, unknown>;
}

export const refundRequestReferencedSchema: Schema<RefundRequestReferenced> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    merchant: [
      'merchant',
      optional(lazy(() => merchantSubsequentRequestSchema)),
    ],
    amount: ['amount', optional(bigint())],
  },
  'additionalProperties',
  optional(unknown())
);
