/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Actions, actionsSchema } from './actions.js';

export interface RetrieveCaptureResponseActions {
  /** HATEOAS links for response payloads. */
  voidCapture?: Actions;
  additionalProperties?: Record<string, unknown>;
}

export const retrieveCaptureResponseActionsSchema: Schema<RetrieveCaptureResponseActions> = typedExpandoObject(
  { voidCapture: ['voidCapture', optional(lazy(() => actionsSchema))] },
  'additionalProperties',
  optional(unknown())
);
