/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';
import {
  EmvCardInputCode,
  emvCardInputCodeSchema,
} from './emvCardInputCode.js';

/** Clear EMV instrument data for retrieval payloads. */
export interface RetrievalEmvInstrumentClear {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Provides more information about why the EMV Input Mode was used. */
  cardInputCode: EmvCardInputCode;
}

export const retrievalEmvInstrumentClearSchema: Schema<RetrievalEmvInstrumentClear> = object(
  {
    type: ['type', string()],
    cardInputCode: ['cardInputCode', emvCardInputCodeSchema],
  }
);
