/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** SoftPOS instrument data for retrieval payloads. */
export interface RetrievalSoftPosInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  softPosId: string;
}

export const retrievalSoftPosInstrumentSchema: Schema<RetrievalSoftPosInstrument> = object(
  { type: ['type', string()], softPosId: ['softPosId', string()] }
);
