/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Actions, actionsSchema } from './actions.js';

export interface RetrievePaymentResponseActions {
  /** HATEOAS links for response payloads. */
  cancelPayment?: Actions;
  /** HATEOAS links for response payloads. */
  capturePayment?: Actions;
  /** HATEOAS links for response payloads. */
  refundPayment?: Actions;
  /** HATEOAS links for response payloads. */
  voidCapture?: Actions;
  /** HATEOAS links for response payloads. */
  incrementAuthorizedAmount?: Actions;
  additionalProperties?: Record<string, unknown>;
}

export const retrievePaymentResponseActionsSchema: Schema<RetrievePaymentResponseActions> = typedExpandoObject(
  {
    cancelPayment: ['cancelPayment', optional(lazy(() => actionsSchema))],
    capturePayment: ['capturePayment', optional(lazy(() => actionsSchema))],
    refundPayment: ['refundPayment', optional(lazy(() => actionsSchema))],
    voidCapture: ['voidCapture', optional(lazy(() => actionsSchema))],
    incrementAuthorizedAmount: [
      'incrementAuthorizedAmount',
      optional(lazy(() => actionsSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
