/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** PASS token instrument data for retrieval payloads. */
export interface RetrievalPassTokenInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
}

export const retrievalPassTokenInstrumentSchema: Schema<RetrievalPassTokenInstrument> = object(
  { type: ['type', string()] }
);
