/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Encrypted keyed instrument data for retrieval payloads. */
export interface RetrievalKeyedInstrumentEncrypted {
  /** Value indicating the specific type instance for this field. */
  type: string;
}

export const retrievalKeyedInstrumentEncryptedSchema: Schema<RetrievalKeyedInstrumentEncrypted> = object(
  { type: ['type', string()] }
);
