/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { AchAccountType, achAccountTypeSchema } from './achAccountType.js';
import { SecCode, secCodeSchema } from './secCode.js';

/** ACH data for retrieval payloads */
export interface RetrievalAchData {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Truncated ACH/bank account number. */
  truncatedAccount: string;
  /** Routing number of the banking institution. */
  routing: string;
  /** Type of ACH account. */
  accountType?: AchAccountType;
  /** SEC codes for ACH processing */
  secCode?: SecCode;
  checkNumber?: string;
  additionalProperties?: Record<string, unknown>;
}

export const retrievalAchDataSchema: Schema<RetrievalAchData> = typedExpandoObject(
  {
    type: ['type', string()],
    truncatedAccount: ['truncatedAccount', string()],
    routing: ['routing', string()],
    accountType: ['accountType', optional(achAccountTypeSchema)],
    secCode: ['secCode', optional(secCodeSchema)],
    checkNumber: ['checkNumber', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
