/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Clear keyed instrument data for retrieval payloads. */
export interface RetrievalKeyedInstrumentClear {
  /** Value indicating the specific type instance for this field. */
  type: string;
}

export const retrievalKeyedInstrumentClearSchema: Schema<RetrievalKeyedInstrumentClear> = object(
  { type: ['type', string()] }
);
