/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Links, linksSchema } from './links.js';

export interface RetrievePaymentResponseLinks {
  captures?: Links[];
  refunds?: Links[];
  additionalProperties?: Record<string, unknown>;
}

export const retrievePaymentResponseLinksSchema: Schema<RetrievePaymentResponseLinks> = typedExpandoObject(
  {
    captures: ['captures', optional(array(lazy(() => linksSchema)))],
    refunds: ['refunds', optional(array(lazy(() => linksSchema)))],
  },
  'additionalProperties',
  optional(unknown())
);
