/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Actions, actionsSchema } from './actions.js';

export interface RetrieveRefundResponseActions {
  /** HATEOAS links for response payloads. */
  voidRefund?: Actions;
  additionalProperties?: Record<string, unknown>;
}

export const retrieveRefundResponseActionsSchema: Schema<RetrieveRefundResponseActions> = typedExpandoObject(
  { voidRefund: ['voidRefund', optional(lazy(() => actionsSchema))] },
  'additionalProperties',
  optional(unknown())
);
