/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Encrypted swiped instrument data for retrieval payloads. */
export interface RetrievalSwipedInstrumentEncrypted {
  /** Value indicating the specific type instance for this field. */
  type: string;
}

export const retrievalSwipedInstrumentEncryptedSchema: Schema<RetrievalSwipedInstrumentEncrypted> = object(
  { type: ['type', string()] }
);
