/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Placement, placementSchema } from './placement.js';

/** request an SCA exemption from Worldpay. Be SCA compliant and reduce customer checkout friction */
export interface ScaExemption {
  enabled?: boolean;
  /**
   * request an SCA exemption from Worldpay. Be SCA compliant and reduce customer checkout friction
   *   |  |  |
   *   |-----|-----|
   *   | authorization | Request exemption in payment authorization only |
   *   | authentication | Request exemption in authentication (3DS) only   |
   *   | both |  Request exemption in both authorization and authentication (3DS)  |
   */
  placement?: Placement;
  additionalProperties?: Record<string, unknown>;
}

export const scaExemptionSchema: Schema<ScaExemption> = typedExpandoObject(
  {
    enabled: ['enabled', optional(boolean())],
    placement: ['placement', optional(placementSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
