/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  PaymentResultScheduledPayment,
  paymentResultScheduledPaymentSchema,
} from './paymentResultScheduledPayment.js';

/** Response payload for scheduled payment execution data. */
export interface ScheduledPaymentExecution {
  /** One-based index of the task run. */
  sequenceNumber: number;
  /** Date and time in ISO-8601 format indicating the scheduled start of the task run. */
  scheduledStartTime: string;
  /** Actual date and time in ISO-8601 format indicating when the task was started. */
  actualStartTime: string;
  /** Scheduled payment response payload */
  paymentResult: PaymentResultScheduledPayment;
  additionalProperties?: Record<string, unknown>;
}

export const scheduledPaymentExecutionSchema: Schema<ScheduledPaymentExecution> = typedExpandoObject(
  {
    sequenceNumber: ['sequenceNumber', number()],
    scheduledStartTime: ['scheduledStartTime', string()],
    actualStartTime: ['actualStartTime', string()],
    paymentResult: [
      'paymentResult',
      lazy(() => paymentResultScheduledPaymentSchema),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
