/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ScheduledPaymentsRunInterval
 */
export enum ScheduledPaymentsRunInterval {
  OneTime = 'oneTime',
  Daily = 'daily',
  Weekly = 'weekly',
  Monthly = 'monthly',
  Annually = 'annually',
  MonthlyLastDay = 'monthlyLastDay',
}

/**
 * Schema for ScheduledPaymentsRunInterval
 */
export const scheduledPaymentsRunIntervalSchema: Schema<ScheduledPaymentsRunInterval> = stringEnum(
  ScheduledPaymentsRunInterval
);
