/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SecCode
 */
export enum SecCode {
  Arc = 'ARC',
  Boc = 'BOC',
  Rck = 'RCK',
  Ccd = 'CCD',
  Ppd = 'PPD',
  Pop = 'POP',
  Tel = 'TEL',
  Web = 'WEB',
}

/**
 * Schema for SecCode
 */
export const secCodeSchema: Schema<SecCode> = stringEnum(SecCode);
