/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  boolean,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Method, methodSchema } from './method.js';
import { TimeFrame, timeFrameSchema } from './timeFrame.js';

export interface Shipping3Ds {
  /** Email address used for an electronic delivery. */
  email?: string;
  /** Flag that indicates whether the customer name on account is identical to the shipping name. */
  nameMatchesAccountName?: boolean;
  /** Shipping method used. */
  method?: Method;
  timeFrame?: TimeFrame;
  additionalProperties?: Record<string, unknown>;
}

export const shipping3DsSchema: Schema<Shipping3Ds> = typedExpandoObject(
  {
    email: ['email', optional(string())],
    nameMatchesAccountName: ['nameMatchesAccountName', optional(boolean())],
    method: ['method', optional(methodSchema)],
    timeFrame: ['timeFrame', optional(timeFrameSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
