/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Address, addressSchema } from './address.js';
import { Phone, phoneSchema } from './phone.js';

/** Shipping information used for fraud assessment, 3DS authentication and the payment itself. */
export interface Shipping {
  /** Customers first name */
  firstName?: string;
  /** Customers last name */
  lastName?: string;
  /** Email address. */
  email?: string;
  /** Phone number. */
  phone?: Phone;
  /** Address data */
  address?: Address;
  additionalProperties?: Record<string, unknown>;
}

export const shippingSchema: Schema<Shipping> = typedExpandoObject(
  {
    firstName: ['firstName', optional(string())],
    lastName: ['lastName', optional(string())],
    email: ['email', optional(string())],
    phone: ['phone', optional(lazy(() => phoneSchema))],
    address: ['address', optional(lazy(() => addressSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
