/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Card-present entry method using a contactless 'Soft POS' device for credit or debit (example: Apple Tap to Pay), when Worldpay is the PSP */
export interface SoftPosInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  emvTlvData: string;
  /** Base-64 encoded string of encrypted data read from the Soft POS device, resulting from the contactless payment attempt. */
  encryptedSoftPosData: string;
}

export const softPosInstrumentSchema: Schema<SoftPosInstrument> = object({
  type: ['type', string()],
  emvTlvData: ['emvTlvData', string()],
  encryptedSoftPosData: ['encryptedSoftPosData', string()],
});
