/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { ThreeRi, threeRiSchema } from './threeRi.js';
import { Usage1, usage1Schema } from './usage1.js';

/** Polymorphic reference for subscription data */
export interface Subscription {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /**
   * Setup an __subscription__ agreement for the following cases... <br> <ul>
   *   <li> (__first__) - The __first__ time this card is being presented, and being stored by the Merchant. </li>
   *   <li> (__subsequent__) - Make a payment using the stored card. This can be a Customer Initiated Transaction (CIT). </li>
   *   <li> (__resubmission__) - Resubmit a previously declined payment. The card holder may have resolved the reason for the original decline, i.e. lack of funds, etc., thus the Payment can be resubmitted. </li>
   *   <li> (__reauthorization_) - Used when the original Authorization needs to be Reauthorized based on a split or future shipment type scenario. </li>
   * </ul>
   * Provide a scheme reference and optionally enable 3RI.
   */
  usage: Usage1;
  /**
   * Unique scheme reference for a repeat agreement between you and the customer. <br>
   * New reference is generated for each subsequent payment. Most but __not all__ issuers return this. <br>
   * Included in the Worldpay Token if created with the initial agreement (first) and therefore not required here.
   */
  schemeReference?: string;
  /**
   * Merchant initiated 3DS authentication on subsequent subscription payments. <br>
   * __3DS must be enabled.__
   */
  threeRi?: ThreeRi;
  additionalProperties?: Record<string, unknown>;
}

export const subscriptionSchema: Schema<Subscription> = typedExpandoObject(
  {
    type: ['type', string()],
    usage: ['usage', usage1Schema],
    schemeReference: ['schemeReference', optional(string())],
    threeRi: ['threeRI', optional(lazy(() => threeRiSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
