/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for SwipedFallbackReasonCode
 */
export enum SwipedFallbackReasonCode {
  MagstripeReadChipReadFailure = 'magstripeReadChipReadFailure',
  MagstripeReadNonTechnicalFallback = 'magstripeReadNonTechnicalFallback',
}

/**
 * Schema for SwipedFallbackReasonCode
 */
export const swipedFallbackReasonCodeSchema: Schema<SwipedFallbackReasonCode> = stringEnum(
  SwipedFallbackReasonCode
);
