/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import {
  TrackDataEncrypted,
  trackDataEncryptedSchema,
} from './trackDataEncrypted.js';

/** Use either TrackData or EncryptedTrackData (when using P2PE) */
export interface SwipedEncryptedPinlessInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** One of the encrypted track data fields must be provided, encrypted track2 is recommended. */
  encryptedTrackData: TrackDataEncrypted;
}

export const swipedEncryptedPinlessInstrumentSchema: Schema<SwipedEncryptedPinlessInstrument> = object(
  {
    type: ['type', string()],
    encryptedTrackData: [
      'encryptedTrackData',
      lazy(() => trackDataEncryptedSchema),
    ],
  }
);
