/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { PinData, pinDataSchema } from './pinData.js';
import {
  SwipedFallbackReasonCode,
  swipedFallbackReasonCodeSchema,
} from './swipedFallbackReasonCode.js';
import { TrackDataClear, trackDataClearSchema } from './trackDataClear.js';

/** Clear card data entered via a swipe */
export interface SwipedClearInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** One of the track data fields must be provided, track2 is recommended. */
  trackData: TrackDataClear;
  /** Security code usually associated with a debit card. */
  pinData?: PinData;
  /** Provides more information about why a lower capability entry mode was used. Do not supply if no EMV fallback occurred. */
  fallbackReasonCode?: SwipedFallbackReasonCode;
}

export const swipedClearInstrumentSchema: Schema<SwipedClearInstrument> = object(
  {
    type: ['type', string()],
    trackData: ['trackData', lazy(() => trackDataClearSchema)],
    pinData: ['pinData', optional(lazy(() => pinDataSchema))],
    fallbackReasonCode: [
      'fallbackReasonCode',
      optional(swipedFallbackReasonCodeSchema),
    ],
  }
);
