/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { PinData, pinDataSchema } from './pinData.js';
import {
  SwipedFallbackReasonCode,
  swipedFallbackReasonCodeSchema,
} from './swipedFallbackReasonCode.js';
import {
  TrackDataEncrypted,
  trackDataEncryptedSchema,
} from './trackDataEncrypted.js';

/** Use either TrackData or EncryptedTrackData (when using P2PE) */
export interface SwipedEncryptedInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** One of the encrypted track data fields must be provided, encrypted track2 is recommended. */
  encryptedTrackData: TrackDataEncrypted;
  /** Security code usually associated with a debit card. */
  pinData?: PinData;
  /** Provides more information about why a lower capability entry mode was used. Do not supply if no EMV fallback occurred. */
  fallbackReasonCode?: SwipedFallbackReasonCode;
}

export const swipedEncryptedInstrumentSchema: Schema<SwipedEncryptedInstrument> = object(
  {
    type: ['type', string()],
    encryptedTrackData: [
      'encryptedTrackData',
      lazy(() => trackDataEncryptedSchema),
    ],
    pinData: ['pinData', optional(lazy(() => pinDataSchema))],
    fallbackReasonCode: [
      'fallbackReasonCode',
      optional(swipedFallbackReasonCodeSchema),
    ],
  }
);
