/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { TrackDataClear, trackDataClearSchema } from './trackDataClear.js';

/** Clear card data without a PIN entered via a swipe */
export interface SwipedClearPinlessInstrument {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** One of the track data fields must be provided, track2 is recommended. */
  trackData: TrackDataClear;
}

export const swipedClearPinlessInstrumentSchema: Schema<SwipedClearPinlessInstrument> = object(
  {
    type: ['type', string()],
    trackData: ['trackData', lazy(() => trackDataClearSchema)],
  }
);
