/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** System error */
export interface SystemError {
  /** High-level, human-readable classification of the error. */
  title?: string;
  /** Human-readable description of the system error. */
  message?: string;
}

export const systemErrorSchema: Schema<SystemError> = object({
  title: ['title', optional(string())],
  message: ['message', optional(string())],
});
