/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/**
 * Merchant initiated 3DS authentication on subsequent subscription payments. <br>
 * __3DS must be enabled.__
 */
export interface ThreeRi {
  /** End date of the subscription. */
  endDate: string;
  /** End date of the subscription. */
  frequency: number;
  /** Identifier for the directory server transaction from the prior authentication; typically, this value is in UUID format. */
  transactionId: string;
  /** Identifier for the ACS transaction from the prior authentication; typically, this value is in UUID format. */
  acsTransactionId: string;
  /** Identifier for the ACS transaction from the prior authentication. */
  authenticationTimeStamp: string;
  additionalProperties?: Record<string, unknown>;
}

export const threeRiSchema: Schema<ThreeRi> = typedExpandoObject(
  {
    endDate: ['endDate', string()],
    frequency: ['frequency', number()],
    transactionId: ['transactionId', string()],
    acsTransactionId: ['acsTransactionId', string()],
    authenticationTimeStamp: ['authenticationTimeStamp', string()],
  },
  'additionalProperties',
  optional(unknown())
);
