/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** One of the track data fields must be provided, track2 is recommended. */
export interface TrackDataClear {
  track1?: string;
  track2?: string;
  track3?: string;
}

export const trackDataClearSchema: Schema<TrackDataClear> = object({
  track1: ['track1', optional(string())],
  track2: ['track2', optional(string())],
  track3: ['track3', optional(string())],
});
