/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import {
  KeyedOrSwipedEncryptedFormat,
  keyedOrSwipedEncryptedFormatSchema,
} from './keyedOrSwipedEncryptedFormat.js';

/** One of the encrypted track data fields must be provided, encrypted track2 is recommended. */
export interface TrackDataEncrypted {
  keySerialNumber: string;
  /** Device manufacturer and family-specific encryption format for card present transactions */
  encryptedFormat: KeyedOrSwipedEncryptedFormat;
  encryptedTrack1Data?: string;
  encryptedTrack2Data?: string;
}

export const trackDataEncryptedSchema: Schema<TrackDataEncrypted> = object({
  keySerialNumber: ['keySerialNumber', string()],
  encryptedFormat: ['encryptedFormat', keyedOrSwipedEncryptedFormatSchema],
  encryptedTrack1Data: ['encryptedTrack1Data', optional(string())],
  encryptedTrack2Data: ['encryptedTrack2Data', optional(string())],
});
