/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for UnitOfMeasure
 */
export enum UnitOfMeasure {
  C = 'C',
  G = 'G',
  K = 'K',
  L = 'L',
  O = 'O',
  P = 'P',
  Q = 'Q',
  U = 'U',
  Z = 'Z',
}

/**
 * Schema for UnitOfMeasure
 */
export const unitOfMeasureSchema: Schema<UnitOfMeasure> = stringEnum(
  UnitOfMeasure
);
