/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AmountWithCurrency1,
  amountWithCurrency1Schema,
} from './amountWithCurrency1.js';
import { Links, linksSchema } from './links.js';
import {
  PaymentMethodResponseUnreferencedRefund,
  paymentMethodResponseUnreferencedRefundSchema,
} from './paymentMethodResponseUnreferencedRefund.js';
import {
  RefundResponseActions,
  refundResponseActionsSchema,
} from './refundResponseActions.js';

/** Response payload for unreferenced refund requests */
export interface UnreferencedRefundResponse {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Globally unique identifer defined by Worldpay. */
  commandId?: string;
  /** Globally unique identifer defined by Worldpay. */
  refundId?: string;
  /** Outcome of the request; one of the following: refused | refunded */
  outcome: string;
  /** Date and time, conforming to the ISO-8601 specification, that the transaction was received and processed. */
  dateTime: string;
  /** the value and currency */
  amount?: AmountWithCurrency1;
  /** Response data specific to the payment method. */
  paymentMethod?: PaymentMethodResponseUnreferencedRefund;
  /** HATEOAS links for response payloads. */
  links?: Links;
  actions?: RefundResponseActions;
  additionalProperties?: Record<string, unknown>;
}

export const unreferencedRefundResponseSchema: Schema<UnreferencedRefundResponse> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    commandId: ['commandId', optional(string())],
    refundId: ['refundId', optional(string())],
    outcome: ['outcome', string()],
    dateTime: ['dateTime', string()],
    amount: ['amount', optional(lazy(() => amountWithCurrency1Schema))],
    paymentMethod: [
      'paymentMethod',
      optional(lazy(() => paymentMethodResponseUnreferencedRefundSchema)),
    ],
    links: ['_links', optional(lazy(() => linksSchema))],
    actions: ['_actions', optional(lazy(() => refundResponseActionsSchema))],
  },
  'additionalProperties',
  optional(unknown())
);
