/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { Usage2, usage2Schema } from './usage2.js';

/** Polymorphic reference for unscheduled CoF data */
export interface Unscheduled {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /**
   * Setup an __Unscheduled__ agreement for the following cases... <br> <ul>
   *   <li> (__first__) - The __first__ time this card is being presented, and being stored by the Merchant. </li>
   *   <li> (__subsequent__) - This is typically associated with a Merchant Initiated Transaction (MIT). </li>
   *   <li> (__resubmission__) - Resubmit a previously declined payment. The card holder may have resolved the reason for the original decline, i.e. lack of funds, etc., thus the Payment can be resubmitted. </li>
   *   <li> (__reauthorization_) - Used when the original Authorization needs to be Reauthorized based on a split or future shipment type scenario. </li>
   * </ul>
   */
  usage: Usage2;
  /**
   * Unique scheme reference for a repeat agreement between you and the customer. <br>
   * New reference is generated for each subsequent payment. Most but __not all__ issuers return this. <br>
   * Included in the Worldpay Token if created with the initial agreement (first) and therefore not required here.
   */
  schemeReference?: string;
  additionalProperties?: Record<string, unknown>;
}

export const unscheduledSchema: Schema<Unscheduled> = typedExpandoObject(
  {
    type: ['type', string()],
    usage: ['usage', usage2Schema],
    schemeReference: ['schemeReference', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
