/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MerchantSubsequentRequest,
  merchantSubsequentRequestSchema,
} from './merchantSubsequentRequest.js';
import {
  ScheduledPayment,
  scheduledPaymentSchema,
} from './scheduledPayment.js';

/** Request payload to update a scheduled payment */
export interface UpdatePaymentScheduleRequest {
  /** Subsequent request merchant object. */
  merchant: MerchantSubsequentRequest;
  /** Payment scheduling parameters */
  schedule: ScheduledPayment;
  additionalProperties?: Record<string, unknown>;
}

export const updatePaymentScheduleRequestSchema: Schema<UpdatePaymentScheduleRequest> = typedExpandoObject(
  {
    merchant: ['merchant', lazy(() => merchantSubsequentRequestSchema)],
    schedule: ['schedule', lazy(() => scheduledPaymentSchema)],
  },
  'additionalProperties',
  optional(unknown())
);
