/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Usage3
 */
export enum Usage3 {
  First = 'first',
  Subsequent = 'subsequent',
  Resubmission = 'resubmission',
}

/**
 * Schema for Usage3
 */
export const usage3Schema: Schema<Usage3> = stringEnum(Usage3);
