/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Usage1
 */
export enum Usage1 {
  First = 'first',
  Subsequent = 'subsequent',
  Resubmission = 'resubmission',
  Reauthorization = 'reauthorization',
}

/**
 * Schema for Usage1
 */
export const usage1Schema: Schema<Usage1> = stringEnum(Usage1);
