/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Usage
 */
export enum Usage {
  First = 'first',
  Subsequent = 'subsequent',
  Resubmission = 'resubmission',
  Reauthorization = 'reauthorization',
}

/**
 * Schema for Usage
 */
export const usageSchema: Schema<Usage> = stringEnum(Usage);
