/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Usage2
 */
export enum Usage2 {
  First = 'first',
  Subsequent = 'subsequent',
  Resubmission = 'resubmission',
  Reauthorization = 'reauthorization',
}

/**
 * Schema for Usage2
 */
export const usage2Schema: Schema<Usage2> = stringEnum(Usage2);
