/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Usertype
 */
export enum Usertype {
  GuestUser = 'guestUser',
  RegisteredUser = 'registeredUser',
  FederatedAccount = 'federatedAccount',
  IssuerCredentials = 'issuerCredentials',
  ThirdPartyAuthentication = 'thirdPartyAuthentication',
  FidOauthEnticator = 'fidoAuthenticator',
}

/**
 * Schema for Usertype
 */
export const usertypeSchema: Schema<Usertype> = stringEnum(Usertype);
