/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

/** Validation error */
export interface ValidationError {
  /** High-level classification for the error. */
  title: string;
  /** JSON pointer to the field that triggered the validation error. */
  jsonPointer?: string;
  /** Human-readable description of the validation error. */
  message?: string;
}

export const validationErrorSchema: Schema<ValidationError> = object({
  title: ['title', string()],
  jsonPointer: ['jsonPointer', optional(string())],
  message: ['message', optional(string())],
});
