/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  number,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** the value and currency */
export interface Value {
  /** Three-digit currency code. See list of supported currencies. */
  currency: string;
  /** Amount, if provided must include the currency. */
  amount: number;
  additionalProperties?: Record<string, unknown>;
}

export const valueSchema: Schema<Value> = typedExpandoObject(
  { currency: ['currency', string()], amount: ['amount', number()] },
  'additionalProperties',
  optional(unknown())
);
