/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  AmountWithCurrency1,
  amountWithCurrency1Schema,
} from './amountWithCurrency1.js';
import {
  PaymentMethodResponseSubsequentOffline,
  paymentMethodResponseSubsequentOfflineSchema,
} from './paymentMethodResponseSubsequentOffline.js';

/** Response payload for void requests. */
export interface VoidResponse {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Globally unique identifer defined by Worldpay. */
  commandId?: string;
  /** Outcome of the request; one of the following: refused | voided. */
  outcome: string;
  /** Date and time, conforming to the ISO-8601 specification, that the transaction was received and processed. */
  dateTime: string;
  /** the value and currency */
  amount?: AmountWithCurrency1;
  /** Response data specific to the payment method. */
  paymentMethod?: PaymentMethodResponseSubsequentOffline;
  additionalProperties?: Record<string, unknown>;
}

export const voidResponseSchema: Schema<VoidResponse> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    commandId: ['commandId', optional(string())],
    outcome: ['outcome', string()],
    dateTime: ['dateTime', string()],
    amount: ['amount', optional(lazy(() => amountWithCurrency1Schema))],
    paymentMethod: [
      'paymentMethod',
      optional(lazy(() => paymentMethodResponseSubsequentOfflineSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
