/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  lazy,
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import {
  MerchantSubsequentRequest,
  merchantSubsequentRequestSchema,
} from './merchantSubsequentRequest.js';

/** Void a specific batch-impacting "leg" of a payment (capture or refund). */
export interface VoidRequest {
  /** Unique reference generated by you that is used to identify a payment throughout its lifecycle. */
  reference?: string;
  /** Subsequent request merchant object. */
  merchant?: MerchantSubsequentRequest;
  additionalProperties?: Record<string, unknown>;
}

export const voidRequestSchema: Schema<VoidRequest> = typedExpandoObject(
  {
    reference: ['reference', optional(string())],
    merchant: [
      'merchant',
      optional(lazy(() => merchantSubsequentRequestSchema)),
    ],
  },
  'additionalProperties',
  optional(unknown())
);
