/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';
import { CardBrand, cardBrandSchema } from './cardBrand.js';

/** Worldpay OmniToken instrument */
export interface WorldpayOmniToken {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** Issued OmniToken. */
  token: string;
  /** Enumeration of card brands supported by across Worldpay platforms */
  brand: CardBrand;
  additionalProperties?: Record<string, unknown>;
}

export const worldpayOmniTokenSchema: Schema<WorldpayOmniToken> = typedExpandoObject(
  {
    type: ['type', string()],
    token: ['token', string()],
    brand: ['brand', cardBrandSchema],
  },
  'additionalProperties',
  optional(unknown())
);
