/**
 * Express Payments APILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  optional,
  Schema,
  string,
  typedExpandoObject,
  unknown,
} from '../schema.js';

/** Access token */
export interface Worldpay {
  /** Value indicating the specific type instance for this field. */
  type: string;
  /** token namespace */
  namespace?: string;
  /** description of token */
  description?: string;
  additionalProperties?: Record<string, unknown>;
}

export const worldpaySchema: Schema<Worldpay> = typedExpandoObject(
  {
    type: ['type', string()],
    namespace: ['namespace', optional(string())],
    description: ['description', optional(string())],
  },
  'additionalProperties',
  optional(unknown())
);
